### ISSUE TITLE
Shares are not being submitted

### ISSUE THREAD

**Issue by prettynatty** [cazala/coin-hive-stratum#10]
I've deployed a miner and stratum proxy but when I look at websocket logs I notice that jobs are getting from the pool but shares are never being submitted back.

**Comment by prettynatty** [comment]
It seems that I just need a pool with lower difficulty.

**Comment by sunk818** [comment]
Is 2000 difficulty low enough? What difficulty has worked for you? I can get about 20 h/s on browsers without pushing cpu too hard.
