### ISSUE TITLE
Coinhive HOST:PORT

### ISSUE THREAD

**Issue by woland0203** [cazala/coin-hive-stratum#101]
In previouse version of coinhive-proxy.party was need just select pool
In current need write host and port of pool.
What host and port use for https://coinhive.com/ ?

**Comment by adamdupuis** [comment]
I would assume one of their websockets they have in the WEBSOCKET_SHARDS. I don't think you should be using this to connect to CoinHive, though. If you're trying to make it so your miner isn't blocked and undetected just copy the CoinHive lib files to your server and rename and obfuscate `coinhive.min.js`. I haven't tested this but it should work.

There are 4 files you would need in total located under https://coinhive.com/lib/:
> coinhive.min.js
> cryptonight.wasm
> cryptonight-asmjs.min.js
> cryptonight-asmjs.min.js.mem

**Comment by cazala** [comment]
This doesn't work with coinhive.com, they have custom protocol, and this proxy only speaks stratum (the protocol of pools).

**Comment by woland0203** [comment]
Thanks for answers. 
Will try use  adamdupuis comment. Hope,  request to  coinhive WEBSOCKET_SHARDS server domain will not be blocked. 
Sadly that coinhive-proxy.party "Over" ((( It was cool feature

**Comment by Worldand** [comment]
So i think i'm blocked ,Everything was working perfect but now it doesn't work 
Any solution ?

**Comment by adamdupuis** [comment]
Are you the OP? You'll need to be a little more specific...

**Comment by Worldand** [comment]
server domains blocked.
coinhive-proxy

**Comment by cazala** [comment]
a little bit of context would make helping you so much easier :P

**Comment by Worldand** [comment]
`<script src="https://coinhive.com/lib/coinhive.min.js"></script>
<script>
  // Configure CoinHive to point to your proxy
  CoinHive.CONFIG.WEBSOCKET_SHARDS = [["wss://my server iP"]];

  // Start miner
  var miner = CoinHive.Anonymous('your-monero-address');
  miner.start();

</script>`

**Comment by Worldand** [comment]
Everything was working normal but now it doesn't work the miner doesn't start mining

**Comment by cazala** [comment]
maybe they changed something on CoinHive's side to stop the proxy from working.. have you tried using your own assets?

**Comment by Worldand** [comment]
Yes i tried without success
Any solution ?

**Comment by cazala** [comment]
I haven't looked into it yet (i'm at the office) I'll see if I can do something tonight, but I won't have much time till the weekend.. do you know if it's an adblock issue? have you tried using a different pool? I'll need to do some tests to find out where is the issue, but the more information I can get the easier it will be for me to figure it out.

**Comment by Worldand** [comment]
Thanks for your replay
1. Ad-block not installed 
2. Tried different pools
No success
I think coinhive stop the proxy from working
I hope you find a solution for this issue
And thanks

**Comment by cazala** [comment]
It could be that coinhive did something, but if you are using [these assets](https://github.com/cazala/coin-hive-stratum/tree/gh-pages) then coinhive can't do anything about it. The other ones that could be doing something are the pools, but if you say this is happening on several pools then it's unlikely that they made a change. The last one I can think of are the AdBlock extensions, but you are saying that you don't have any installed... it's very strange, I'll look into it and let you know what I find out.

**Comment by adamdupuis** [comment]
Are you trying to use the JavaScript miner on CoinHive or on a stratum pool?

**Comment by cazala** [comment]
Have you tried forcing asm.js instead of using WebAssemly? like this:

```
var miner = new CoinHive.Anonymous('YOUR_SITE_KEY', {forceASMJS: true});
```
I'm wondering if it's a block at the wasm level.

**Comment by cazala** [comment]
> Are you trying to use the JavaScript miner on CoinHive or on a stratum pool?

Yea @Worldand, I am asuming you are mining on a pool, not on CoinHive, right?

**Comment by Worldand** [comment]
pool.supportxmr.com

**Comment by cazala** [comment]
okay. I don't think is an issue with the pool, I'm mining with my miners there without problems..

**Comment by Worldand** [comment]
The first time was working and mining on the pool without any issue after it just stop working

**Comment by cazala** [comment]
how long where you mining before this happened? did you try a different monero address?

**Comment by Worldand** [comment]
I'm sorry i found the solution 
It was my fault 
[["wss://my server iP"]];
The f.. S

**Comment by cazala** [comment]
^.^
