### ISSUE TITLE
[Dissociation] Integrate this project with xmr-node-proxy for better hashrate

### ISSUE THREAD

**Issue by akaddn** [cazala/coin-hive-stratum#107]
Hi,
I just found this project very interesting!
I am use it on my website with a lot of visitors and getting nice hashrate, But, i believe it should be higher (it was higher when I worked directly with Coinhive).

Then I found this project: https://github.com/Snipa22/xmr-node-proxy, that aim to increase the hashrate: _"If you are managing more than 10 miners, check out xmr-node-proxy, a proxy specifically designed for our pool software. It will allow you to manage and direct your workers in an efficient manner."_

Can it works together with coin-hive-stratum?
Is anyone tried it before?

**Comment by CineXMike** [comment]
Yes this works,
Just use his setup guide!

**Comment by JBelinchon** [comment]
Hi I am interested on this topic. You said coin-hive-stratum can work together with xmr-node-proxy, 
Could you please elaborate how to do this? Maybe chaining one tho another?

**Comment by akaddn** [comment]
Does anyone have statistics, how much does it improve?
