### ISSUE TITLE
Mining ETN Problem

### ISSUE THREAD

**Issue by Worldand** [cazala/coin-hive-stratum#108]
Hello
I have a problem in mining etn 
proxy > 2017-12-16 13:34: shares accepted (dff16933-4fd9-4001-bf59-48184191b921): 2                                                         
proxy > 2017-12-16 13:36: job submitted (dff16933-4fd9-4001-bf59-48184191b921): 152788817589651                                             
proxy > 2017-12-16 13:36: pool connection error (dff16933-4fd9-4001-bf59-48184191b921): {"code":-1,"message":"Invalid job id"} 
proxy > proxy error: undefined

**Comment by PiTi2k5** [comment]
Yes it is normal on various ETN Pools with cryptonote-universal-pool, but the miners restart immediately. I run this proxy since 3 weeks and i get fullspeed and runs perfect
