### ISSUE TITLE
How to login to SupportXMR

### ISSUE THREAD

**Issue by manojdcoder** [cazala/coin-hive-stratum#110]
I'm able to connect to SupportXMR pool, not sure what is my login credentials (miner name part of password field).

**Comment by cazala** [comment]
you can see your stats at supportxmr.com by entering you monero wallet address in the dashboard

**Comment by manojdcoder** [comment]
@cazala Thanks but my question was different. In order to increase the threshold we have to login. So any idea what should be the miner name for login?

**Comment by cazala** [comment]
ah, according to their Getting started page, you need to provide an email in your password, like: `coin-hive-stratum --pass=workerName:mail@domain.com`

then you can log into supportxmr.com dashboard using your monero wallet address and the email part in your password: `mail@domain.com`

**Comment by manojdcoder** [comment]
Thanks for the clarification, it worked 👍
