### ISSUE TITLE
Not working, miner disconected 4 hour ago

### ISSUE THREAD

**Issue by vsystech** [cazala/coin-hive-stratum#111]
Dear Developer, i have a problem with stratum script. running 8 hour without problem. after i'm looking some "unauthencited" try restart the proxy, stop start. but hashrate drop down. miners not reconnect. 

restart the server, 4 hour ago only looking this logs. 

http://prntscr.com/hor9ms

**Comment by vsystech** [comment]
Using the latest version: {"version":"2.6.4"}

starting with 
coin-hive-stratum 8892 --host=pool.supportxmr.com --port=3333
command

**Comment by cazala** [comment]
are you using `CoinHive.Anonymous` or `CoinHive.User` to instantiate your miners?

**Comment by vsystech** [comment]
CoinHive.User(with wallet address, and worker name) but i'm said the proxy is worked to 8 - 9 hour. before have a first problem. and when restart the proxy. get the connect disconnect error. and no hash speed, no shares) 

http://prntscr.com/hor9ms

**Comment by cazala** [comment]
are you running with `pm2`?

**Comment by vsystech** [comment]
no, start with
coin-hive-stratum 8892 --host=pool.supportxmr.com --port=3333

maybe you have a skype ?

**Comment by vsystech** [comment]
i'm start proxy on other server, and looking few logs. 

http://prntscr.com/hou90e

**Comment by vsystech** [comment]
Now working again the server, http://prntscr.com/hou9m7

but elapsed 6 hour. and no hashes. os share submit. only connect - disconnect.

**Comment by vsystech** [comment]
Don't get reply but i have other problem. i have a 16 gb ram dedicated server, running the script but after 1500~ connection not accept more. only write 0 hashes per sec. why ? please help me solve this problem.

**Comment by vidoza** [comment]
Yesterday I also started to have problem with that proxy. Almost all the time "miner disconnected" information. I also noticed big decrease of efficiency. I am running proxy with pm2 and in rush hour I have more than 10k miners.

**Comment by cazala** [comment]
does it go back to normal if you reset it (stop/start) ? 10k miner is a heavy load, how many instances of the proxy are you running? you can set the number of instances using the `-i` flag, like `pm2 start proxy -i 4`

**Comment by vsystech** [comment]
not back to normal started the server but wait 4-5 hour to working again and send shares.
. if try start with pm not starting and get error if check pm monit.

**Comment by vsystech** [comment]
currently running the server try connect from browser miner. 10/7 try connect to server but 
Core: 2 Hashes/s : 0 Total Hashes/s : 0 Total Accept : 0

and not starting the miner.

**Comment by cazala** [comment]
it appears that this starts to happen after an `Unauthorized` occurs. Something similar has been reported in #105, but I don't know if this is a pool issue (like a pool ban) in that case restarting the server won't help if the IP was blacklisted or something (maybe due to too many connections). Once I had my monero address swiped by a proxy because I had to many connections. If this happens again I encourage you to try a different monero address or mining on a different pool, like `https://moneroocean.stream/` (`gulf.moneroocean.stream:80` has a difficulty of only `100`) and see if this still happens. I  still don't know what causes that `Unauthorized` but I want to figure out if the decrement in hashrate that comes afterwards is a pool ban or an issue with the proxy.

**Comment by cazala** [comment]
Something that helps to mitigate the load is having more than one proxy running (like one on port `9000`, another on port `9001` and so forth). then you can add several proxies in the WEBSOCKET_SHARDS array:

```js
CoinHive.CONFIG.WEBSOCKET_SHARDS = [["ws://my-proxy.com:9000", "ws://my-proxy.com:9001", ...]];
```

**Comment by cazala** [comment]
Apparently this is also an issue that happens when using `CoinHive.User` and not `CoinHive.Anonymous`... do you know how many different "users" do you have?

**Comment by vsystech** [comment]
yes, currently 6 different user. sorry user is fix, my wallet address but use 6-7 worker.

**Comment by vsystech** [comment]
i'm start proxy on different port. 

{
  "miners": 2709,
  "connections": 1
}

{
  "miners": 140,
  "connections": 1
}

when try connect to first, not start hashing.

the second start immediatelly, so not problem with my server resources. but i don't understand. maybe limit on port connection or what ?

**Comment by vsystech** [comment]
and i have a some problem with x25 coinhive stratum. after 1000-1500 miner not connect new miners 0 hash 0 share. currently i use 4 proxy with 3 different server. and i think is suck :D

**Comment by cazala** [comment]
mm yes, that's not got. the proxy should have 1 connection every 100 miners, and I can see that your proxy has 2709 using the same single TCP connection... are you running using the CLI? try this:

```
coin-hive-stratum 8892 --host=HOST --port=PORT --miners-per-connection=1
```

**Comment by vsystech** [comment]
i'm try nothing changes. 

{
  "miners": 99,
  "connections": 1
}

**Comment by cazala** [comment]
sorry! my bad, the flag is `--max-miners-per-connection=1`

**Comment by vsystech** [comment]
wooow, that is a new error on dash.

http://prntscr.com/hp4nlh

**Comment by cazala** [comment]
okay, how are your `/stats` now?

**Comment by cazala** [comment]
that's probably because of too many connections now.

**Comment by vsystech** [comment]
{
  "miners": 838,
  "connections": 849
}

{
  "miners": 330,
  "connections": 341
}

**Comment by cazala** [comment]
yea, that's why. what if you try `--max-miners-per-connection=200` ? It should be `100` by default but for some reason your connections where stuck on a single one...

**Comment by vsystech** [comment]
wooow, i think now better the situation i get more +8kh/s speed. 

so use 200 on correct value ?

**Comment by cazala** [comment]
yes so far people have reported that 100-250 miners per connection is working fine. I don't know why your proxy was stuck on a single connection... do you remember if your `/stats` have always shown a single connection? 

My assumption is that the proxy had always a single TCP connection and at some point there were too many miners using it and messages started to drop. The proxy doesn't purge connections so I don't think that it went from many connections to a single one, but instead it started with a single one and never created more.

Please let me know if this starts to happen again :)

**Comment by vsystech** [comment]
yes always 1 connection. on three machine :) i'm try install now to 4th machine this script but when run install.sh get a problem. 


npm ERR! code ENOSELF
npm ERR! Refusing to install package with name "coin-hive-stratum" under a package
npm ERR! also called "coin-hive-stratum". Did you name your project the same
npm ERR! as the dependency you're installing?
npm ERR!
npm ERR! For more information, see:
npm ERR!     <https://docs.npmjs.com/cli/install#limitations-of-npms-install-algorithm>

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-12-18T15_29_42_702Z-debug.log

installed other (x25) script. how can i remove ? maybe this is the problem.

**Comment by cazala** [comment]
mm did you clone this repo and then run the `curl` inside that repo? The error you are getting is becuase you are doing an `npm install coin-hive-stratum` on a directory that has a `package.json` with that name already.

Make sure you run the instalation `curl` from `~/`

**Comment by cazala** [comment]
so you still have a single tcp connection per proxy?

**Comment by vsystech** [comment]
yes, but now setup 100 and working as good. 

{
  "miners": 803,
  "connections": 9
}

{
  "miners": 607,
  "connections": 7
}

{
  "miners": 891,
  "connections": 10
}

after restart not reconnect all miner.

**Comment by cazala** [comment]
ahh okay, so when you passed the `--max-miners-per-connection=100` it worked. And before that you were running just `coin-hive-stratum 8892 --host=pool.supportxmr.com --port=3333` without the flag, right?

It's so weird that your proxy was stuck in a single connection... anyway, I just released a patch (`v2.6.5`) that logs the max miners per connection when the proxy is started, to make it easier to figure out when this is the problem.

**Comment by vsystech** [comment]
Okay :) have a great job and thanks your help!

**Comment by cazala** [comment]
no problem!

**Comment by vsystech** [comment]
Sorry to bother you again :( how can i calculate earning to workers ? i'm working on this problem 2 days ago :( maybe you have a great idea ?
