### ISSUE TITLE
Vps server slow 

### ISSUE THREAD

**Issue by patrickbau** [cazala/coin-hive-stratum#112]
Hello
My vps server became very slow after reaching 60 miners 
Is that normal ?
I'm expecting more x4

**Comment by cazala** [comment]
which are the specs of your VPS? there are several users running this proxy with 
a few thousands of miners.

**Comment by patrickbau** [comment]
1 Core 
1 Go RAM
2 To trafic

**Comment by cazala** [comment]
that sounds about right, it doesn't seem to be consuming much resources.

**Comment by patrickbau** [comment]
Ok
Thank you for your clarification
;)
