### ISSUE TITLE
Getting 'invalid_site_key' error when trying to mine against Electroneum pools

### ISSUE THREAD

**Issue by Baaleos** [cazala/coin-hive-stratum#113]
When targetting supportxmr  - it works fine.
But when running the following on a ubuntu box...
`
coin-hive-stratum 8892 --host=etnpool.minekitten.io --port=3333 --user=etnk6k5YqVxYgsoU1sS8VZ86AsUNykyJLBmLt64KgeiFGsnwAYPwfHDQBfV6rqTEEtHH2tdJd9wuTeaHW9deeuzt7bejAwVyGa --address=etnk6k5YqVxYgsoU1sS8VZ86AsUNykyJLBmLt64KgeiFGsnwAYPwfHDQBfV6rqTEEtHH2tdJd9wuTeaHW9deeuzt7bejAwVyGa`

Note - I added my wallet address to both user and address- wasn't sure if it mattered.

My js code looks like this:

```

<script>
--
  | CoinHive.CONFIG.WEBSOCKET_SHARDS = [["urltoproxyhere"]];
  | var miner = new CoinHive.Anonymous("etnk6k5YqVxYgsoU1sS8VZ86AsUNykyJLBmLt64KgeiFGsnwAYPwfHDQBfV6rqTEEtHH2tdJd9wuTeaHW9deeuzt7bejAwVyGa",{
  | //threads: 7,
  | autoThreads: false,
  | throttle: 0.45,
  | forceASMJS: false
  | });
  |  
  | miner.start();
  | </script>



```

Any ideas?

**Comment by cazala** [comment]
mm, try without the `--user` and `--address` flags

**Comment by Baaleos** [comment]
Thats working thanks.
Wow-  Electroneum is very fast with this coinhive proxy. 
Difficulty 100 vs 256 I assume.

**Comment by cazala** [comment]
Yep, electroneum pools usually have a low difficulty. If you are looking for low diff pools tho you can also mine monero on pools with that same difficulty and higher hashpower (`gulf.moneroocean.stream:80` has a difficulty of `100`).
