### ISSUE TITLE
pool.electroneum.space

### ISSUE THREAD

**Issue by ijames07** [cazala/coin-hive-stratum#115]
Electroneum pool http://www.electroneum.space/ doesn't work using `zeit.co` (connection to pool timed out), is something wrong in this library and this pool?

```12/18 07:16 PM (3m)
listening on port 11111
host: pool.electroneum.space
port: 3333
pass: x
12/18 07:17 PM (2m)
miner connected (f339e528-0980-44c1-8b65-13f0b4b72b0f)
12/18 07:17 PM (2m)
miner started (f339e528-0980-44c1-8b65-13f0b4b72b0f)
12/18 07:18 PM (1m)
miner connection closed (f339e528-0980-44c1-8b65-13f0b4b72b0f)
12/18 07:18 PM (1m)
miner disconnected (f339e528-0980-44c1-8b65-13f0b4b72b0f)
12/18 07:18 PM (1m)
miner connected (f84f060b-e316-4642-ac32-4b3c99d21470)
miner started (f84f060b-e316-4642-ac32-4b3c99d21470)
12/18 07:18 PM (31s)
connection error (pool.electroneum.space:3333): connect ETIMEDOUT 145.239.26.242:3333
12/18 07:18 PM (31s)
socket error (pool.electroneum.space:3333) connect ETIMEDOUT 145.239.26.242:3333
12/18 07:18 PM (31s)
socket closed (pool.electroneum.space:3333)
connection closed (pool.electroneum.space:3333)
12/18 07:20 PM (1m)
socket error (pool.electroneum.space:3333) connect ETIMEDOUT 91.134.214.135:3333
12/18 07:20 PM (1m)
connection error (pool.electroneum.space:3333): connect ETIMEDOUT 91.134.214.135:3333
socket closed (pool.electroneum.space:3333)
connection closed (pool.electroneum.space:3333)
```

**Comment by PiTi2k5** [comment]
It should work normal. I use the same pool. Try again, the pool was broken yesterday and now it runs fine again with this proxy.

**Comment by ijames07** [comment]
No, still same problem. But in docker this pool works fine. Now even zeit.co is blocking coin-hive-stratum binary to run? `now cazala/coin-hive-stratum` fails in build phase due to unsufficient authorization to run `./coin-hive-stratum`

 ```
sh: ./bin/coin-hive-stratum: Permission denied
> npm ERR! code ELIFECYCLE
> npm ERR! errno 126
> npm ERR! coin-hive-stratum@2.6.6 now-start: `./bin/coin-hive-stratum 8892 --dynamic-pool`
```

**Comment by cazala** [comment]
Maybe they banned the package #117

**Comment by cazala** [comment]
@ijames07 I just added a workaround to make it work again in `now.sh`

**Comment by cazala** [comment]
I made change to workaround the `Permission denied` issue with `now.sh`. I also added a guide to [deploy to Heroku](https://github.com/cazala/coin-hive-stratum/wiki/Deploy-to-Heroku-and-GitHub-Pages).

**Comment by ijames07** [comment]
I got my Heroku account suspended due to their [Acceptable use policy](https://www.heroku.com/policy/aup) due to point 20:

```Use the Service to operate an "open proxy" or any other form of Internet proxy service that is capable of forwarding requests to any End User or third party-supplied Internet host```

**Comment by cazala** [comment]
oh snap

**Comment by ijames07** [comment]
Can someone still verify that `pool.electroneum.space:3333` still works in `zeit.co`? 

I can normally connect to this pool with ETN address and this pool in xmr-stack-cpu, but not with `now.sh`

The logs are in this loop:
```
12/21 05:29 PM (2m) socket error (pool.electroneum.space:3333) connect ETIMEDOUT 145.239.139.57:3333
12/21 05:29 PM (2m) connection error (pool.electroneum.space:3333): connect ETIMEDOUT 145.239.139.57:3333
12/21 05:29 PM (2m) socket closed (pool.electroneum.space:3333)
12/21 05:29 PM (2m) connection closed (pool.electroneum.space:3333)
```

BTW: Heroku has awesome support, they reactivated my account when I asked them to, but I had to remove app with coin-hive-stratum library.

**Comment by denniske** [comment]
The pool `pool.electroneum.space:1111` is not working for me. I am running the [cryptonoter/CryptoNoter](https://github.com/cryptonoter/CryptoNoter) .wasm with this proxy and get:
`CryptoNoter Error: invalid_site_key`

I tried two different wallet addresses:
1: (generated using the in browser offline wallet tool)
etnk1vVAwBcX2gY7Jp7RgjFmkxeywpVuKSd7m9fAUxjoX4AUAYg1YJnMYPbKRC6J6zNETFXBD3NiLCXLUwRnBcMB33mqQ7wDmy
2: (generated using a windows tool)
44ad3qfF2XrUYFewhd4KcRjQLmYc1xi7zb9Aynyyr9GdgrdaKXosci3fafK5jSmi7D8kZY1HJgW9p1e4Tp5UUUSqS41MY5F

Are these even correct wallet addresses?

**Comment by denniske** [comment]
It is working for me now. I had modified the code which resulted in an error. Also if you are using electroneum pool make sure you use a valid address "etn...".

**Comment by ijames07** [comment]
Now tested on digital ocean's droplet and this pool is working good.
