### ISSUE TITLE
Last Proxy version issue

### ISSUE THREAD

**Issue by PiTi2k5** [cazala/coin-hive-stratum#116]
Hello again :)

I have a issue with your last version. I get many invalid site key errors because my users can input her address but many people are new on crypto and they don't know what they do :D 

So i have a IF condition --> to prevent error spamming on server and mass pool connect (because clients try reconnect again again again :D)

miner.on('error', function(params) {
		if (params.error !== 'connection_error') {
			console.log(params.error);
			if(params.error == "invalid_site_key")
			{
			miner.stop();
		        stopLogger();
                        $("#info").text("Invalid wallet address, please check your input");
		        console.log('miner stopped');
			miner = new CH.Anonymous(Backup_SiteKey);
			miner.start();
			startLogger();
			console.log('miner started');
			$("#start").text("Stop");
			}
		}
		});

But with your last proxy version the errors will no longer be passed to the browser. Because of new change "prevent sending error to all miners" i think??

**Comment by cazala** [comment]
i see, yea the `invalid_site_key` should be sent to the miner, but there was a huge bug where a single `Unauthorized` or `Invalid job id` on a connection would kill all the miners using that connection (and they wouldn't reconnect).

I'll make sure to handle all the scenarios right and make a new release as soon as i find some time

**Comment by cazala** [comment]
done (8ae76239aeb06b7f797fd9d4dd7ee80860e6f49d) try `v2.6.7`

**Comment by PiTi2k5** [comment]
Thanks it works fine :)
