### ISSUE TITLE
Failed submit shares after some days running

### ISSUE THREAD

**Issue by letlet** [cazala/coin-hive-stratum#119]
Nodejs 8.9.3 CHS  2.5.0 
CHS is running OK for some days(like 2-5 days) then failed submit any shares. Only miner connected or miner disconnected or job submitted mesage in the PM2 console, no job arrived and shares accepted message.
Then upgrade to CHS 2.6.5, same situation happened after some days .

**Comment by adamdupuis** [comment]
Not sure if it will solve anything, but CHS is now on v2.6.7.

**Comment by letlet** [comment]
Yes, I have upgraded to v2.6.7  and will have another try.

**Comment by letlet** [comment]
use v2.6.7 and same situation happened.
error log:
pool connection error (9d3821f1-9e82-497a-8fa9-e9dfdfb00069): {"code":-1,"message":"Unauthenticated"}
proxy error: undefined
pool connection error (e200b14a-74ef-4109-97fd-be532e3ee9d5): {"code":-1,"message":"Unauthenticated"}
proxy error: undefined
pool connection error (f4da19d1-d9ac-484b-9ae8-83b2dbed0928): {"code":-1,"message":"Unauthenticated"}
proxy error: undefined
pool connection error (119482e4-7af7-462f-8955-fa5d51733ac7): {"code":-1,"message":"Unauthenticated"}
proxy error: undefined
pool connection error (78297f00-2fa5-4f04-a41e-3a1058586026): {"code":-1,"message":"Unauthenticated"}
proxy error: undefined
pool connection error (12c15d07-51f3-425c-a84c-a6e8937eadf2): {"code":-1,"message":"Unauthenticated"}
proxy error: undefined
pool connection error (d2a12614-72e9-492b-b28e-d67fcdffabf2): {"code":-1,"message":"Unauthenticated"}
proxy error: undefined
pool connection error (423f1c6b-1360-4187-9d31-3f77cb439c58): {"code":-1,"message":"Unauthenticated"}
proxy error: undefined
pool connection error (aed9cd8d-a138-414d-b680-a5ba153df04d): {"code":-1,"message":"Unauthenticated"}
proxy error: undefined
pool connection error (59d510d1-8866-4da0-aa20-5598b4005037): {"code":-1,"message":"Unauthenticated"}
proxy error: undefined
pool connection error (d7266560-e002-456e-a528-53bb8599ead0): {"code":-1,"message":"Unauthenticated"}
