### ISSUE TITLE
never get hash

### ISSUE THREAD

**Issue by Jackie0911** [cazala/coin-hive-stratum#12]
I run the python program, but never seen the js miner submit hashes and always get the target info. When i use others js miner,it's normal.How should i do?

**Comment by cazala** [comment]
which python program...?

**Comment by cazala** [comment]
Probably you connected to a pool with a high difficulty. Take into account coinhive has a difficulty of 256 while nanopool.org has 150k and minexmr.com has a configurable difficulty but with a minimum of 10k. So it will take longer to submit jobs on a custom pool (but the reward will be higher as well).
