### ISSUE TITLE
By default, how much resource does it use on visitors' devices?

### ISSUE THREAD

**Issue by psycholyzern** [cazala/coin-hive-stratum#121]
Title.

**Comment by adamdupuis** [comment]
How much CPU usage? All available unless you set a throttle.

**Comment by psycholyzern** [comment]
@adamdupuis You mean, max usage unless I throttled?

**Comment by adamdupuis** [comment]
Yes.

**Comment by psycholyzern** [comment]
Okay thanks a lot.
I should give some mercy to mobile user then😅.
