### ISSUE TITLE
2.6.7 - Shares per minute drop substantially after a short period.

### ISSUE THREAD

**Issue by matthewlilley** [cazala/coin-hive-stratum#125]
Works perfectly for about 10 minutes. Then shares per minute drops to about 20% of what's expected. Only way to bring it back to normal is a full restart of the process. There's no errors, but number of miners keep growing and growing. Tested on 2.6.6 also, and the same issue there.

Using pm2 and maxMinersPerConnection 100, on a $20 DO box.

**Comment by neverknoww** [comment]
Today I also having issue with the hash rates. 
Dropped a lot compare to yday.

Pool Graph: https://imgur.com/a/kaAGy 
Hash Rates: https://imgur.com/a/0nLHm 

Anyone having the same problem as me?

**Comment by davidfowler5452** [comment]
same issue here the miners gets disconnected and they won't reconnect unless the page is refreshed

**Comment by vphelipe** [comment]
What is the pool you are using?
