### ISSUE TITLE
connection refused

### ISSUE THREAD

**Issue by procloud** [cazala/coin-hive-stratum#13]
tcp socket created
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED 104.XXX.XXX.XXX:3333
    at Object._errnoException (util.js:1021:11)
    at _exceptionWithHostPort (util.js:1043:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1175:14)

**Comment by cazala** [comment]
which version are you using?

**Comment by procloud** [comment]
i did an npm install of your package last week. its the current version i presume

**Comment by cazala** [comment]
#16 was merged yesterday and released under `v1.1.2`, that's the one you should be using @procloud

**Comment by procloud** [comment]
thanks will update
