### ISSUE TITLE
Not working on Now.sh

### ISSUE THREAD

**Issue by Demuss** [cazala/coin-hive-stratum#133]
Hello

I followed the steps to deploy git on Now.sh

/stats is not showing connected miners, and keep working on coinhive

**Comment by curvedb** [comment]
Same here. Tried Heroku also and my account suspended instantly

**Comment by Demuss** [comment]
Status for instance is frozen. Need new free alternate solution to host this proxy

**Comment by Demuss** [comment]
I already found public proxy. 
Thank you

**Comment by Wolf-Byte** [comment]
@Demuss please could you met me know the alternative?

**Comment by Wolf-Byte** [comment]
let*

**Comment by Demuss** [comment]
If your site is on https it wont work.
