### ISSUE TITLE
do you have example that display some UI details about hashes/s, submitted, accepted?

### ISSUE THREAD

**Issue by sunk818** [cazala/coin-hive-stratum#17]
Okay, I was able to set it up so that hashes are being accepted. On the browser URLs, there's no details showing up for me. I tried to use coinhive's miner UI but JS in your example doesn't like working with `<script src="https://coinhive.com/lib/miner.min.js" async></script>` ... so, I'm kind of lost how we can have some UI.

I know your node.js app coin-hive has a UI which is very helpful to me.

Any thoughts on including an example that integrates your coin-hive example? Or at least point in the direction to experiment?

**Comment by korzhyk** [comment]
I use a very, very simple UI in my miner `iframe`.

````js
  function showMinerInfo (miner) {
    if (typeof info === 'undefined') {
      document.body.innerHTML = "<pre id='info'><input type='checkbox' id='running' style='vertical-align:middle'/> Speed:<i id='speed'></i> Threads:<i id='threads'></i> Throttle:<i id='throttle'></i> Total:<i id='total'></i> Accepted:<i id='accepted'></i></pre>"
    }
    running.onclick = function toggleStartStop () { miner[this.checked ? 'start' : 'stop']() }
    var update = function () {
      running.checked = miner.isRunning()
      speed.innerText = miner.getHashesPerSecond().toFixed(2) + 'H/s'
      threads.innerText = miner.getNumThreads()
      throttle.innerText = miner.getThrottle()
      total.innerText = miner.getTotalHashes()
      accepted.innerText = miner.getAcceptedHashes()
    }
    update()
    setInterval(update, 1e3)
  }
````
This function `showMinerInfo(miner)` put some HTML in document body and update info every second. Checkbox  is interactive and can `start` or `stop` the miner instance.

**Comment by sunk818** [comment]
wow, thank you! I was reading about innerHTML and document.write myself... this is great! I'm very grateful!
