### ISSUE TITLE
Queue class — why is it required?

### ISSUE THREAD

**Issue by elmigranto** [cazala/coin-hive-stratum#18]
Hello, I've been wondering why message queueing is required? If I understand everything correctly, it buffers all socket.io messages from the client and processes them at max rate of 1 per second per client. Why is it this way?

Thanks.

**Comment by cazala** [comment]
When there's a new ws connection, a new tcp connection is created to the pool. While that connection is being created, messages might start to arrive from the ws (like login message) and the tcp connection might not be ready yet. The queue ensures those messages are sent to the pool once the tcp connection is up

**Comment by elmigranto** [comment]
It seems that delay stays even after connection is established. So even after we opened a socket, message rate is still limited to 1 message per client per second.

**Comment by cazala** [comment]
Yes, it's not the best solution. Once the connection is up we should just pipe the messages from one socket to the other without the queue in the middle

**Comment by cazala** [comment]
@elmigranto [I tweaked the queue](https://github.com/cazala/coin-hive-stratum/commit/a77cf78c0a0b75d73de1303394ea2ab4826e83fc) so after the connection is stablished and the queue is cleared, the new messages get emitted right away instead of being queued and emitted every 1 sec:
