### ISSUE TITLE
Doesn't connect any other pools 

### ISSUE THREAD

**Issue by hackable** [cazala/coin-hive-stratum#2]
Doesn't connect to other pools such as minemonero.pro or minexmr.com

**Comment by Dustymcp** [comment]
we had the same problem how long you been running it ?

**Comment by hackable** [comment]
i debugged it doesn't login  in other pools there must be a stratum protocol error

**Comment by cazala** [comment]
Hi, it was a dumb error, I didn't add the end of like `\n` at the end of the stratum message, for some reason that wan't needed for `nanopool.org` but it was breaking things for other pools. I just tried this using the version `1.0.1` that I just released and it's working:

```js
require('coin-hive-stratum')({
  host: 'pool.minexmr.com',
  port: 4444,
  log: true
}).listen(8892)
```
