### ISSUE TITLE
Where is the log file?

### ISSUE THREAD

**Issue by sunk818** [cazala/coin-hive-stratum#20]
Running 1.1.2 now. Wondering where the log file is? Is there a log file written by default? 

Stratum Proxy crashed, but I do not know why.

Tried to look for `defaults.log` but did not find any.

Do I need to explicitly use `--log` in the CLI and define a log file name?

I tried `--log=true` and `--log=stratum.log` but neither produced a log file.

I've resorted to piping `coin-hive-stratum 8892 --host=xmr-eu1.nonapool.org --port 14444 > stratum.log & `

**Comment by cazala** [comment]
there's no log file

**Comment by cazala** [comment]
It would be nice to have one tho

**Comment by sunk818** [comment]
I think mostly output to the individual miners would be most helpful even if it is the raw output from the stratum proxy. Right now it's all mixed in with all the miners hitting the proxy. I'm thinking of using worker name so I can associate the id number with worker name.

**Comment by cazala** [comment]
I just added (f7672896be656538e7651a380dd94beeeec2a79b)  a `logFile` parameter that allows you to store the logs in a file. It is released under version `1.2.0`. You can check it in the [API doc](https://github.com/cazala/coin-hive-stratum#api)

**Comment by sunk818** [comment]
What is the exactly command line parameter if I want to output to a log file?

I tried a few variations but failed to create a log file.

**Comment by sunk818** [comment]
`--log-file=stratum_proxy.log` saves it to the current directory!

**Comment by cazala** [comment]
yes, it should save it to the dir where you ran the cli
