### ISSUE TITLE
unexpected token

### ISSUE THREAD

**Issue by procloud** [cazala/coin-hive-stratum#21]
message from pool to miner:

 {"jsonrpc":"2.0","method":"job","params":{"blob":"0606f2e29acf058dbd19588559dcc1474a4c0d9a421ac24ae4517d041a08ab746ae1920a26e5b2000000003a35b9b633ff69cd36e4289b259b475fbaab1f2bb28387690cb2b204f924297c08","job_id":"mdnhZmzgeqgktI1XoXBT3eVMmOGp","target":"9bc42000","id":"7b8c1476-ad8e-4ebb-bd51-b7289e0590a0"}}
{"jsonrpc":"2.0","method":"job","params":{"blob":"0606f2e29acf058dbd19588559dcc1474a4c0d9a421ac24ae4517d041a08ab746ae1920a26e5b2000000003a35b9b633ff69cd36e4289b259b475fbaab1f2bb28387690cb2b204f924297c08","job_id":"mdnhZmzgeqgktI1XoXBT3eVMmOGp","target":"9bc42000","id":"7b8c1476-ad8e-4ebb-bd51-b7289e0590a0"}}

undefined:2
{"jsonrpc":"2.0","method":"job","params":{"blob":"0606f2e29acf058dbd19588559dcc1474a4c0d9a421ac24ae4517d041a08ab746ae1920a26e5b2000000003a35b9b633ff69cd36e4289b259b475fbaab1f2bb28387690cb2b204f924297c08","job_id":"mdnhZmzgeqgktI1XoXBT3eVMmOGp","target":"9bc42000","id":"7b8c1476-ad8e-4ebb-bd51-b7289e0590a0"}}
^

SyntaxError: Unexpected token { in JSON at position 310
    at JSON.parse (<anonymous>)
    at Socket.<anonymous> (/usr/local/lib/node_modules/coin-hive-stratum/src/proxy.js:137:25)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:264:12)
    at readableAddChunk (_stream_readable.js:251:11)
    at Socket.Readable.push (_stream_readable.js:209:10)
    at TCP.onread (net.js:587:20)

**Comment by cazala** [comment]
mm it looks like two jobs got concat'd together? I can try to catch that so it doesn't kill the server, but that's so weird tho

**Comment by cazala** [comment]
Actually, this has been addressed already. [Here](https://github.com/cazala/coin-hive-stratum/blob/master/src/proxy.js#L63-L67) and [there](https://github.com/cazala/coin-hive-stratum/blob/master/src/proxy.js#L147-L155). Try using `v1.1.3`.
