### ISSUE TITLE
What about parcentage of profit?

### ISSUE THREAD

**Issue by MrGreyhat** [cazala/coin-hive-stratum#24]
Do they (coinhive.com) still get 30% of the mining?

**Comment by cazala** [comment]
If you use this proxy you wouldn't be mining on coinhive's pool, so no, there's not 30% commission. The commission is set by the pool you are mining on (ie, `nanopool.org` and `minexmr.com` have 1% commissions).

**Comment by sunk818** [comment]
Be mindful of the minimum payout required at any given pool. Some require 1 XMR so unless you have a high hash rate could be awhile.

**Comment by cazala** [comment]
True, I think `nanopool.org` is on 1 XMR minimum and `mineXMR.com` is 0.5 XMR.. also take into account that these pools have higher difficulty. nanopool has a fixed difficulty of 120k and mineXMR has a minimum difficulty of 10k, while coinhive has a difficulty of just 256.. This make the miner to take longer to send jobs, but also the reward of a job sent to one of these pools is tens or thousands of times higher.

**Comment by sunk818** [comment]
Here are a list of pools: http://moneropools.com/

I don't endorse them, but they have a lower starting difficulty of 3000: https://www.usxmrpool.com/

If you're trying to mine with devices with lower hash rates like 20-40 H/s, using a pool with a lower difficulty may be more beneficial. This will give you a better opportunity to submit at least one accepted share before a new block gets introduced. Again, not an endorsement... just my opinion.

**Comment by MrGreyhat** [comment]
Thank You for your kind information!  @cazala @sunk818

**Comment by QuantumLeaper** [comment]
@cazala do you think it would be beneficial to set a fixed difficulty of 256 on a private pool, or have the starting_difficulty of 1000 with a variance minimum diff of 256?
