### ISSUE TITLE
Does this function with CoinHive's new 'AuthMine'

### ISSUE THREAD

**Issue by BlueSkyGreenMeadow** [cazala/coin-hive-stratum#26]
I am speaking of this:

https://coinhive.com/blog/authedmine

When I use coin-hive-stratum alongside Authmine, the Authmine captcha fails to show itself. The reason I am using Authmine is because it is whitelisted by anti-virus, I do not want my website visitors being bothered by anti-virus alerts; should I just use minero.pw or will that also be detected by anti-virus? Let me know what you think.

**Comment by sunk818** [comment]
the coin-hive uses the site key on coinhive along with any monero address. I have a feeling in the short-term coin-hive site key and monero address has to be included. long term, might need to have a separate JS that is based on coinhive but be an independent fork.

**Comment by cazala** [comment]
I just added a tool to workaround the adblock issue: [CoinHive Proxy](https://coinhive-proxy.party)

**Comment by thedotmack** [comment]
I love you guys 😻

**Comment by cazala** [comment]
There's a guide for workarounding the adblock issue: https://github.com/cazala/coin-hive-stratum/wiki/Deploy-to-now.sh-and-GitHub-Pages
