### ISSUE TITLE
Error: connect ECONNREFUSED xxx.xxx.xxx.xxx:3333

### ISSUE THREAD

**Issue by sunk818** [cazala/coin-hive-stratum#27]
[Oct 20th 12:54] message from pool to miner: {"jsonrpc":"2.0","method":"job","params":{"blob":"0202a6d7a6cf05df9e21962484f20b226cf439ec439da083e37ada0eada44277ceb0950f141ba500000000af36c4730de78a8f4e4a7fda08d00fd8bb22525cc771b048f4e8f8afc3f6550f02","job_id":"327312388550490","target":"9bc42000"}}

[Oct 20th 12:54] message sent to miner: {"type":"job","params":{"blob":"0202a6d7a6cf05df9e21962484f20b226cf439ec439da083e37ada0eada44277ceb0950f141ba500000000af36c4730de78a8f4e4a7fda08d00fd8bb22525cc771b048f4e8f8afc3f6550f02","job_id":"327312388550490","target":"9bc42000"}}

[Oct 20th 12:55] connection to pool closed
...
[Oct 20th 12:55] connection to pool closed

[Oct 20th 12:55] new websocket connection

[Oct 20th 12:55] queue created

[Oct 20th 12:55] tcp socket created

[Oct 20th 12:55] new websocket connection

[Oct 20th 12:55] queue created

[Oct 20th 12:55] tcp socket created

events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED xxx.xxx.xxx.xxx:3333
    at Object._errnoException (util.js:1019:11)
    at _exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1175:14)

**Comment by cazala** [comment]
This was fixed by f2910dca5421d2438d66a72a8cfa20ac6c0eccbf, the error handler were being created AFTER the connection was successful, so if the connection fails there were no handlers in place to take care of it.

**Comment by cazala** [comment]
This is part of `v1.4.2`
