### ISSUE TITLE
Adding SSL Certs?

### ISSUE THREAD

**Issue by QuantumLeaper** [cazala/coin-hive-stratum#3]
I'm not too good with Node, but want to get better! Is there a way to add SSL certs to the proxy for secure WSS connections?

**Comment by cazala** [comment]
You will need to tweak the [WebSocket Server](https://github.com/cazala/coin-hive-stratum/blob/master/src/proxy.js#L201),  to [support SSL](https://github.com/websockets/ws/blob/master/examples/ssl.js#L8-L19), but it's not supported as it is now.

**Comment by cazala** [comment]
or you can host it on `now.sh` and it will get `wss://` out of the box

**Comment by cazala** [comment]
Now you can thanks to #16
