### ISSUE TITLE
Error -1 Unauthenticated error

### ISSUE THREAD

**Issue by sunk818** [cazala/coin-hive-stratum#30]
Is anyone getting any Unauthenticated error in the stratum proxy output?

I can't determine if this is the pool or the stratum proxy. Just wondering if others are running into something similar.

The error doesn't appear right away, but might take 30 minutes to several hours. 

I've been killing node every hour then restarting the coin-hive-stratum ... not sure if it is the pool or the node.js app

**Comment by procloud** [comment]
i think there may be a blind try/catch in the code to handle unauths, but i have not looked to verify myself. this blind try / catch may need to run the initial connect procedure again on catching unauths

**Comment by procloud** [comment]
if a graceful close is sent to the miner ws client, the client will try to reconnect and be reauthed. that would be more of a work around since a more graceful exchange may be available, but i am not familiar enough yet to say.

**Comment by CineXMike** [comment]
I got like the same problem,
But i think this happens randomly, Only more frequent with allot of connections.
