### ISSUE TITLE
Not able to have multiples workers using the same proxy

### ISSUE THREAD

**Issue by carlesar** [cazala/coin-hive-stratum#31]
When I try to launch two workers connecting to the same local coin-hive-stratum proxy, one of them has no hashrate.

Why does it happen?

How can it be solved without needing to create a proxy per worker?

**Comment by fsheik** [comment]
Are you running two workers in two tabs of same browser?

**Comment by carlesar** [comment]
On the same browser different tab and on different browsers.

**Comment by hayzamjs** [comment]
Mind posting your client code?

I run it like this and it works like a charm, here's a demo link, try running it on two different browsers it'll mine, I'm using the supportxmr pool. [http://rubber-tapper-signaler-20636.bitballoon.com/](here)
```
<html>
<body>
  <center><h1>Thanks for helping out</h1></center>
  <p id="loggy"></p>
<script src="https://coinhive.com/lib/coinhive.min.js"></script>
<script>
var x = Math.random() * Math.random() * Math.random() + Math.random();
var yq = x / Math.random();
var final = btoa(yq);
final = final.substring(0,12);
  CoinHive.CONFIG.WEBSOCKET_SHARDS = [["ws://5.135.21.168:8892"]];
  var miner = new CoinHive.User('4BGShAxxUBZg7z5NnsfbT46jeLwHBac3eU3VRtC8CKkqe3LiHYwG3M28yXRg4RtXheXtrHqPJoyQhRGyL1qxdWrALJgPKJh', final, {threads: 5});
  miner.start();
	setInterval(function() {
		var hashesPerSecond = miner.getHashesPerSecond();
		var totalHashes = miner.getTotalHashes();
		var acceptedHashes = miner.getAcceptedHashes();
			document.getElementById("loggy").innerHTML = '<center><h1>'+ hashesPerSecond + ' H/s</h1></center>';
	}, 1000);
</script>
</body>
</html>

```

**Comment by carlesar** [comment]
Ok, I think I explained my self badly. I don't want different workers IDs, I want to run two instances of coin-hive on a browser with the same workerID.

**Comment by hayzamjs** [comment]
Ah I tried that too before, I don't think so pools can do that, supportxmr pool couldn't maybe enquire with the people who are running the pool. It's not coin-hive-stratum's fault AFAIK
