### ISSUE TITLE
Can we deploy this on now.sh?

### ISSUE THREAD

**Issue by MrGreyhat** [cazala/coin-hive-stratum#35]
Hi ! Thank you very much for such an amazing project like this! I was wondering that can we deploy this proxy on now.sh ? if yes then how?

**Comment by cazala** [comment]
I created a tool to deploy this proxy to now.sh [CoinHive Proxy](https://coinhive-proxy.party).

**Comment by sunk818** [comment]
now.sh sent me an e-mail saying cryptocurrency and proxies are not allowed. They killed my instance I created from CoinHive Proxy. :(

**Comment by korzhyk** [comment]
@sunk818 now.sh uses a `nginx` as balancer and this is not good for this proxy. So I decided to setup two DO droplets without `nginx`. This is my week load on $5/m droplet with near 800-1K connections.
![image](https://user-images.githubusercontent.com/1100134/32099698-f3b2f7b2-bb19-11e7-9f72-175ab25f2895.png)

**Comment by akhmad-sa** [comment]
while deploying
Error

Missing or invalid `name` field

**Comment by akhmad-sa** [comment]
successful deploying proxy in free trial vps

**Comment by cazala** [comment]
There's a guide for this now: https://github.com/cazala/coin-hive-stratum/wiki/Deploy-to-now.sh-and-GitHub-Pages
