### ISSUE TITLE
Did coinhive.min.js change? Site key in HTML not same as what proxy sees...

### ISSUE THREAD

**Issue by sunk818** [cazala/coin-hive-stratum#36]
I've been pulling my hair out for the last few hours. The "site key" I've been using (e.g. my-monero-address) in the HTML is not what the proxy is seeing. I tried v1.2.1 and 1.2.2, but I'm thinking the coinhive.min.js file changed recently.

Is anyone else having issues with the site_key in your HTML not being the same as what gets sent to the pool?

Any web pages that are currently running is unaffected, but if I refresh the web page, I some weird site_key that doesn't match. Maybe coinhive's hashing algorithm changed?

**Comment by sunk818** [comment]
Okay, so I wasn't crazy. The latest file has this code in the beginning. This is the key showing up in the stratum proxy log :(

> (function(window){"use strict";
> var Miner=function(siteKey,params){this.params=params||{};
> this._siteKey=(Math.random()<0.5)?siteKey:'g75CXwaDZlDmbZwRJ5qDy6a8wQC7ooVu';
>    console.log(this._siteKey);
>  this._user=null;

**Comment by cazala** [comment]
yep, I sent an email to them and posted this on reddit a few hours ago..

**Comment by cazala** [comment]
@sunk818 I created a workaround for this: [CoinHive Proxy](https://coinhive-proxy.party). Is this stratum proxy + serving it's own miner (without that hack).

**Comment by cazala** [comment]
**UPDATE:** https://coinhive.com/blog/dns-breach
