### ISSUE TITLE
Implementation of xmr-node-proxy?

### ISSUE THREAD

**Issue by QuantumLeaper** [cazala/coin-hive-stratum#37]
Hey, I was wondering if there would be a way to implement this: https://github.com/Snipa22/xmr-node-proxy but with per worker id tracking (total hashes & hashrate). As I understand, it takes multiple workers (example: 4k+) and treats them as one, so there's minimal connections to the pool itself instead of sending all of those connections straight to the pool

**Comment by korzhyk** [comment]
I recently see this project and figureout how to implement `WebSockets` instead of plain node `net.Socket`. I can play with this on my weekend.

**Comment by procloud** [comment]
you should just be able to point the coin-hive proxy to the xmr-node-proxy. ive thought of doing this myself, but have not tested it yet.

also, implementation with https://github.com/xmrig/xmrig-proxy would be more advantageous... its scales far better than xmr-node-proxy, but requires nicehash_nonce support on the pool side.

perhaps coin-hive-stratum can implement nicehash protocol support on the pool side.

**Comment by sunk818** [comment]
How many concurrent can xmr-node-proxy handle vs xmrig-proxy? I wonder how many webmasters would exceed concurrent that xmr-node-proxy can handle.

Downside to single worker is the higher difficulty but low hash rate per device. You may get less acceptable hashes because of the higher difficulty.

**Comment by cazala** [comment]
Now with version `v1.4.0` there's only one TCP connection per monero address, when it used to be one TCP connection per websocket. This should mitigate the pools blowing up due to 1000's of TCP connections.

**Comment by sunk818** [comment]
What is the impact to pool difficulty? Will the pool see the same monero address as one worker? The proxy will send new work instructions downstream to all the different hashers, but the pool only sends the proxy one new work instruction?

**Comment by cazala** [comment]
The pool will get the same messages as before, but they will arrive on the same socket instead of individual ones. The content of the messages has not been changed. This improves the performance but it shoudn't change the way things were working before.

**Comment by sunk818** [comment]
I see. Just read more about xmr-node-proxy. Seems like it splits the work among the different miners without duplication of effort. Better hash rate. I gotta look at pointing coin-hive-stratum --> xmr-node-proxy --> mining pool

from [https://supportxmr.com](https://supportxmr.com) :

> unlike other solutions, it will appear to the pool as a single miner requesting work at normal rate, but at the cumulative difficulty the miners connected to the backend are capable of. This not only potentially reduces the load on the pool servers dramatically, but also allows for more efficient mining. First tests have shown a dramatic increase of hashrate especially with low hashrate miners.

**Comment by Snipa22** [comment]
The TCP connection drawdown is only one part of the benefit to XNP.  Functionally, CHS now acts like Atrides proxy, which means it makes a single TCP connection, then routes all traffic over that, sending individual logins.  This is auctually worse for a pool, then making large numbers of connections, as you may have multiple thousands of miners on a single TCP connection, which is why you're seeing the slowdowns when making single TCP connections, as you're now locking share validations to a single core, rather than somewhat distributing them.

Also, proxies that act like Atrides tend to get packets dropped due to excessive size.

**Comment by slayerulan** [comment]
@Snipa22 are there plans for publish that private project?
Thanks

**Comment by Snipa22** [comment]
@slayerulan Not really, the main proxy barely sees donations as it is, and it's been developed in private for agreements for donations/funding for future development of the proxy.

If there's a group that wants to raise funds to have it released, I'm not against it, but based on the amount of deployments I've helped with, and the size of those deployments, I suspect less than 7-10% of the hashrate using XNP is actually donating anything from it at this time, and that's only ticked up in the last week or two I think as coin-hive-stratum has started to take off and people are getting banned from pools for attaching thousands of tiny miners to them.

**Comment by slayerulan** [comment]
@Snipa22 I see, how much fundraiser do we need for that?

**Comment by Snipa22** [comment]
@slayerulan Unsure at the moment.  The implementation and time spent on XNP is slowly catching up with the funds being raised.  At the moment, the current rate of donations from private sites whom have worked with me, is around 1 XMR/day in terms of hashrate (45-50 kh/s), making it public of course, means that there's no guarantee I would continue to receive this.

**Comment by sunk818** [comment]
So are we talking about integrating into CHS? Doesn't the source code exist on GitHub already?

**Comment by codewatafak** [comment]
Running with --dynamic-pool will fine? Whats happens if coin-hive-stratum server runinng on diffirent pool each connection by end user?

**Comment by cazala** [comment]
`--dynamic-pool` is there to enable deployments to now.sh, if you deploy to your own server you shouldn't use it. but technically yes, when using it each miner can decide to which pool connect to.

**Comment by cazala** [comment]
I'm closing this since in v2 multiple miners can be send thru the same connection, mitigating the problem of having too many tcp connections to the pool
