### ISSUE TITLE
Websocket listens only to IPv6, not IPv4

### ISSUE THREAD

**Issue by janowitz** [cazala/coin-hive-stratum#42]
I got the websocket running but it listens only to the IPv6 address of my server, but not the "standard" IPv4... This may be related to: https://github.com/nodejs/node-v0.x-archive/issues/9195

How can I enforce IPv4 or even enable both?

**Comment by korzhyk** [comment]
You can pass options to `createProxy({ port: 8000, host: '0.0.0.0' })` this options will pass to https://github.com/websockets/ws/blob/master/lib/WebSocketServer.js#L45

**Comment by janowitz** [comment]
Thanks, I already managed to do so... But now struggling with an "Error in connection establishment" probably due to SSL requirements, do you know where to set up the according keys eg.?

**Comment by korzhyk** [comment]
My master branch has ssl support https://github.com/korzhyk/coin-hive-stratum

**Comment by cazala** [comment]
Now with version `v1.4.0` you can pass a `--tls=true` flag or `createProxy({ port: 8000, host: '0.0.0.0', tls: true })` to use TLS to connect to pool.

**Comment by macomrades** [comment]
Hi Cazala, 
Noob here, please how do I use the api? Do I replace the sample contents of proxy.js with with api directives?
Kindly help.
