### ISSUE TITLE
websocket support for ping / pong

### ISSUE THREAD

**Issue by procloud** [cazala/coin-hive-stratum#45]
it appears the coinhive code looks to receive "ping" messages for keep alives

**Comment by procloud** [comment]
perhaps a keep alive forward from the pool?

**Comment by cazala** [comment]
I added keepAlive to the tcp/tls connections to the pool in the version I just released `v1.4.0`

**Comment by procloud** [comment]
great!

**Comment by procloud** [comment]
keep alive for tcp/tls is layer 3/4, possibly still need application layer / pool keep alive

**Comment by cazala** [comment]
in v2 I added keepalived messages that are sent every 30 seconds
