### ISSUE TITLE
Miner not getting JobID's 

### ISSUE THREAD

**Issue by QuantumLeaper** [cazala/coin-hive-stratum#46]
Hey hey,
So just trying out the new version of coin-hive-stratum (v1.4.1) - but for some reason my workers/browser isn't receiving JobID's back from the pool (although the pool is sending them and the coin-hive-proxy is receiving them)

**Comment by cazala** [comment]
Maybe try `v1.4.4`, there was a wrong condition.. 😅  it's working now on my end

**Comment by QuantumLeaper** [comment]
haha ok, excited!

**Comment by QuantumLeaper** [comment]
Woo that fixed it!!

**Comment by cazala** [comment]
Nice! I refactored a lot during the weekend so there might be bugs, please report anything weird you see ^.^
