### ISSUE TITLE
Bad performance when using only one socket

### ISSUE THREAD

**Issue by korzhyk** [cazala/coin-hive-stratum#49]
Today I try to move on new version `1.4.7` and got a really bad results. So I figure out that big problem when using only one socket connection, there are too many messages from miners (online miners count 3-3.5K handled by two proxies) and proxy can't send a large amount of messages to the pool in a time. And we have a long time to auth and hash submission. And result is some miners can't start (not authed and without job) and another can't send hash in time.

**Comment by cazala** [comment]
I see, so 1 tcp connection per websocket kills the pool, and 1 tcp connection per address doesn't work at scale.. I dunno if should I optimize somehow the single tcp connection or have a configurable pool of tcp connections that get reused (say, no more than 100 websockets sharing the same tcp connection).. ideas?

**Comment by justnx** [comment]
How about TCP fastopen Support?

**Comment by korzhyk** [comment]
Looks great to share 1 socket connection for limited users. Also we need to keep in mind that pool `DIFF` is matter and when `DIFF` is low (< 2000) there are too many messages will be sent to pool and when `DIFF` is large there are no heavy load. So maybe a better way to implement a rate-limiter for socket connection? When messages to pool over 200-400 (depending on latency) per second we can create a new socket instance and push new messages to new socket.

**Comment by korzhyk** [comment]
And I prefer for easy solution of `limit miners per socket`.

**Comment by korzhyk** [comment]
@justnx TFO is not about of "speedup" data transmission this is for fast TCP connection (handshake).

**Comment by justnx** [comment]
yes but Perfect for proxies saving you latency and connection sockets

**Comment by procloud** [comment]
i did notice that xmrig proxy claims 100k miners at ~350 connects to pool, which is about 285 miners per pool connect. you may be able to look through that projects code to see how they are distributing this algo.

**Comment by sunk818** [comment]
Does it make sense to consider allocating TCP sockets for specific roles. One TCP socket for authorization & hash submission. Another TCP socket for new difficulty or block announce?

**Comment by cazala** [comment]
This can be configured now with `maxMinersPerConnection` (programatically) or `--max-miners-per-connection` (cli)
