### ISSUE TITLE
feature request: nicehash nonce support

### ISSUE THREAD

**Issue by procloud** [cazala/coin-hive-stratum#50]
i only looked into it briefly, but it appears, that at least, converting the blob to support the nonce is fairly simple. this would also allow use of xmrig-proxy, which happens to be the fastest and most scalable proxy available at the moment.

**Comment by sunk818** [comment]
how do you see @cazala adding a feature like this? would it be a setting in the configuration that would convert the blob to the nicehash nonce? Would you pay a bounty for this feature? Do you have documentation that shows what the conversion would need to be?

**Comment by sudofox** [comment]
I've gotta second this, NiceHash extranonce support is very desirable.

**Comment by sunk818** [comment]
This is from the xmr-stak-cpu `config.txt`:

> Limit the nonce to 3 bytes as required by nicehash. This cuts all the safety margins, and if a block isn't found within 30 minutes then you might run into nonce collisions.

**Comment by sudofox** [comment]
That's correct. However, most people won't be staying on a webpage (the usual spot for a coinhive miner) for thirty minutes unless they're playing games or consuming multimedia content. For the direct BTC payout, nicehash is absolutely lovely.

**Comment by procloud** [comment]
average block time for monero is 2minutes

**Comment by Snipa22** [comment]
This has to be implemented in the miners, not the stratum level software.  CHS serves as a WS -> TCP proxy, and has no control over the NH states, and it's not worth implementing until someone rewrite the webminers to support it.

**Comment by procloud** [comment]
yes, i do see how this is a client-server implementation and not the job of proxy. thanks for the clarification.

**Comment by Vanzent** [comment]
You did the program specifically for the CH? CH does not support nicehash, there is no such function. But it would be very easy to do in CHP. Why not?
