### ISSUE TITLE
Address.xxx: Fixed difficulty vs worker name?

### ISSUE THREAD

**Issue by sunk818** [cazala/coin-hive-stratum#53]
You know some pools accepted address.xxx as fixed difficulty instead of worker name.

**Comment by cazala** [comment]
I guess for those pools you will have to use the `--username` param as the `--dif` param

**Comment by cazala** [comment]
I guess then in those pools then you will need to use CoinHive miner different, and pass the difficult as the username, like `new CoinHive.User('<site-key>', 1000);`
