### ISSUE TITLE
Different between yours and x25's?

### ISSUE THREAD

**Issue by psycholyzern** [cazala/coin-hive-stratum#54]
Title.

**Comment by procloud** [comment]
fundamentally they are same, although i would expect better performance overall from a node.js implementation.

i have tested x25 as well and it also appears to share the same fundamental issue with low hash miners timing out. like @cazala 's implementation is attempting to address, this project has at least an unauth-reauth method, where x25 the miner connection does not.

**Comment by psycholyzern** [comment]
Oh. Good to know. I tried both but couldn't make x25's work. Thank you.
