### ISSUE TITLE
Simple Javascript for Mining WITHOUT Proxies?

### ISSUE THREAD

**Issue by monerominerz** [cazala/coin-hive-stratum#57]
Is there no way to create a Javascipt file that will mine Moneros from a specific pool and just connect directly?

Basically without the need to use a service like now.sh that will just ban your account.  I couldn't find any documentation about why a proxy was needed.  Seems like I should be able to just put in the details for a pool like SupportXRM and my Monero address into a simple Javascript file and start mining :/

Am I missing something?

**Comment by sunk818** [comment]
Yes. The JavaScript is for coinhive. It's not a full blown xmr miner client. The proxy translates the missing pieces the JavaScript doesn't handle to regular xmr pool and vice versa.

**Comment by monerominerz** [comment]
Ahh, ok, that makes sense. :)

Would you happen to now of any Javascipt XMR miner clients that are available?  Specifically one that's pure javascipt, isn't based on CoinHive, doesn't require proxies, etc.

There's a bunch of CoinHive based scripts out there since they got big, just could find anything besides them.

**Comment by sunk818** [comment]
No I don't know of any.

**Comment by procloud** [comment]
you cant make net connections with javascript

**Comment by sunk818** [comment]
If you don't set it up yourself, someone else has to do it for you.

This guy set something up but taking a 10% cut plus whatever the pool takes.

https://www.reddit.com/r/Monero/comments/72hv1a/harvest_distributed_browser_blockchain_monero/

If you plan on doing any sort of scale, you'll end up saving on fees if you roll your own.
