### ISSUE TITLE
How are new job IDs and stale submissions handled?

### ISSUE THREAD

**Issue by sunk818** [cazala/coin-hive-stratum#59]
I'm seeing two potential issues.

1) pool assigns new job (new block?) and proxy seems to be sending it to miner, but doesn't seem to be handled by the client. Web browser should abandon current job and take on the new job right?

2) miner submits stale hash (because new job id was not processed by miner?) and miner connection is killed.

Can you help me troubleshoot here? Seems like the proxy is doing everything correctly... just odd that a new job sent to miner is being ignored. Why would that happen?

> [Nov 13th 10:31] message from miner (161940449965186) {"type":"submit","params":{"job_id":"897294415417127","nonce":"77d427ff","result":"19bd4d03d0008f220cb74aeca75a989cbea60aefd821c2c647616e74c8bd1400"}}
> [Nov 13th 10:31] message sent to pool (my-monero-address): {"id":24,"method":"submit","params":{"id":"161940449965186","job_id":"897294415417127","nonce":"77d427ff","result":"19bd4d03d0008f220cb74aeca75a989cbea60aefd821c2c647616e74c8bd1400"}}
> [Nov 13th 10:31] message from pool (my-monero-address): {"id":24,"jsonrpc":"2.0","error":null,"result":{"status":"OK"}}
> [Nov 13th 10:31] message sent to miner (161940449965186): {"type":"hash_accepted","params":{"hashes":4}}
> [Nov 13th 10:32] message from pool (my-monero-address): {"jsonrpc":"2.0","method":"job","params":{"blob":"0202c2c8a7d0056c2277904f3fff10536b0d3a08c9e5ff832f8ab2248e51984ed79f1c9ef5fbfa0000000076d100f80b8c05535b3850fc5f68077f1060fa8be958dc7c35c28a39904ad17905","job_id":"328325591958127","target":"339a0900"}}
> [Nov 13th 10:32] message from miner (161940449965186) {"type":"submit","params":{"job_id":"897294415417127","nonce":"2643bec7","result":"b23683574fb840ec2694da7caa4a07c6771561310fc1f20f70608a406ee20700"}}
> [Nov 13th 10:32] message sent to pool (my-monero-address): {"id":25,"method":"submit","params":{"id":"161940449965186","job_id":"897294415417127","nonce":"2643bec7","result":"b23683574fb840ec2694da7caa4a07c6771561310fc1f20f70608a406ee20700"}}
> [Nov 13th 10:32] message from pool (my-monero-address): {"id":25,"jsonrpc":"2.0","error":null,"result":{"status":"OK"}}
> [Nov 13th 10:32] message sent to miner (161940449965186): {"type":"hash_accepted","params":{"hashes":5}}
> [Nov 13th 10:32] message from pool (my-monero-address): {"jsonrpc":"2.0","method":"job","params":{"blob":"0202bccaa7d0052c7db258c5390d37ec828ae41b40c6d3de8814166f2a5f75d132a9ae955c0fb500000000dc9d06a37ffd3c94f0b2852b6f0a372d732802034764c1f40baa2e6d3c42237402","job_id":"268833306268788","target":"9bc42000"}}
> [Nov 13th 10:32] message from pool (my-monero-address): {"jsonrpc":"2.0","method":"job","params":{"blob":"0202bccaa7d0052c7db258c5390d37ec828ae41b40c6d3de8814166f2a5f75d132a9ae955c0fb50000000029e77b4d92b75c414c3c41f70a75bf722e0c8f1361c866ffe72710b140aee0cd02","job_id":"355441624135710","target":"339a0900"}}
> [Nov 13th 10:32] message from pool (my-monero-address): {"jsonrpc":"2.0","method":"job","params":{"blob":"0202bccaa7d0052c7db258c5390d37ec828ae41b40c6d3de8814166f2a5f75d132a9ae955c0fb5000000002ec09669b78ecfc454538f34dc6ae770d6145c61f6f191e45151e07c23718a1a02","job_id":"371664476697333","target":"98d70300"}}
> [Nov 13th 10:32] message from pool (my-monero-address): {"jsonrpc":"2.0","method":"job","params":{"blob":"0202bccaa7d0052c7db258c5390d37ec828ae41b40c6d3de8814166f2a5f75d132a9ae955c0fb50000000069d4adb04427d19d3178921c40803c64c615c3528e7e57a302f09ba525966d4f02","job_id":"938075096998363","target":"93180400"}}
> [Nov 13th 10:32] message from pool (my-monero-address): {"jsonrpc":"2.0","method":"job","params":{"blob":"0202bccaa7d0052c7db258c5390d37ec828ae41b40c6d3de8814166f2a5f75d132a9ae955c0fb50000000009600d05d4ce75e5499374e20dbd03925903f63ee6f91291c8533bf545b372a702","job_id":"667537606577389","target":"70c30500"}}
> [Nov 13th 10:32] message from pool (cazala-monero-address): {"jsonrpc":"2.0","method":"job","params":{"blob":"0606c7caa7d0056962c70c001b1d7771654ddbc7a4f9a09773c6f23eca3bc06df673148fa20abd00000000b5e3cd8b459a9d911ee1c8eacccba1dd2044e1473b232aab9ea596aaefc3ec0b16","job_id":"5XCyUFeewriOUmhmeJpCa9enXn0q","target":"37894100","id":"55657949-2e47-47b2-9c46-9b849e2066df"}}
> [Nov 13th 10:32] message from pool (cazala-monero-address): {"jsonrpc":"2.0","method":"job","params":{"blob":"0606c7caa7d0056962c70c001b1d7771654ddbc7a4f9a09773c6f23eca3bc06df673148fa20abd00000000abc6b36cd9f3ade96d30dd09ff4cb76ccb6199c634810891149973820178355516","job_id":"DnS4AUrApOSb27IBwzF/DDAp8Bwx","target":"9bc42000","id":"89df0048-188b-4c91-b332-2def27b18150"}}
> [Nov 13th 10:32] message from pool (cazala-monero-address): {"jsonrpc":"2.0","method":"job","params":{"blob":"0606c7caa7d0056962c70c001b1d7771654ddbc7a4f9a09773c6f23eca3bc06df673148fa20abd000000009572a5d5d7b2cea16fdc5a11a50ae0f3045f30f71d47f3b5d13549a9463fc72c16","job_id":"X3M3Tfz71aVKSeHlZpMDuFdRgpfX","target":"37894100","id":"666946d7-c413-4984-9220-9eeee736b696"}}
> [Nov 13th 10:32] message from pool (cazala-monero-address): {"jsonrpc":"2.0","method":"job","params":{"blob":"0606c7caa7d0056962c70c001b1d7771654ddbc7a4f9a09773c6f23eca3bc06df673148fa20abd000000006c78dbbe4b371cc476943d5b075cea34fd1eebca9f2e2d76680bb97c916696fb16","job_id":"90cRPQBywdv8BsWI+CCwIxb4zUE8","target":"37894100","id":"0e72b93c-7b83-4035-a70f-b75686d70787"}}
> [Nov 13th 10:33] message from miner (unauthenticated) {"type":"auth","params":{"site_key":"cazala-monero-address","type":"anonymous","user":null,"goal":0}}
> [Nov 13th 10:33] message sent to pool (cazala-monero-address): {"id":5,"method":"login","params":{"login":"cazala-monero-address","pass":"donations"}}
> [Nov 13th 10:33] new miner connection
> [Nov 13th 10:33] message from pool (cazala-monero-address): {"id":5,"jsonrpc":"2.0","error":null,"result":{"id":"fa8109b4-bf6b-46d1-a59a-5a089f04b01c","job":{"blob":"0606c7caa7d0056962c70c001b1d7771654ddbc7a4f9a09773c6f23eca3bc06df673148fa20abd00000000495514640ddd34dc42c177fbd6acaf5b19c027d81d7633b5805fbc634f15628f16","job_id":"rcTy6PuqVkX2oUfjbs494R/UgJZN","target":"37894100","id":"fa8109b4-bf6b-46d1-a59a-5a089f04b01c"},"status":"OK"}}
> [Nov 13th 10:33] message from miner (unauthenticated) {"type":"auth","params":{"site_key":"my-monero-address","type":"anonymous","user":null,"goal":0}}
> [Nov 13th 10:33] message sent to pool (my-monero-address): {"id":26,"method":"login","params":{"login":"my-monero-address","pass":"x"}}
> [Nov 13th 10:33] message from pool (my-monero-address): {"id":26,"jsonrpc":"2.0","error":null,"result":{"id":"665513472934253","job":{"blob":"0202bccaa7d0052c7db258c5390d37ec828ae41b40c6d3de8814166f2a5f75d132a9ae955c0fb500000000482599023359e1395f6fa83a015c282793f231e319bcac683db7d88673be64e902","job_id":"113409785064868","target":"9bc42000"},"status":"OK"}}
> [Nov 13th 10:33] miner authenticated (665513472934253)
> [Nov 13th 10:33] there are 2 miners on this pool connection (my-monero-address)
> [Nov 13th 10:33] message sent to miner (665513472934253): {"type":"authed","params":{"token":"","hashes":0}}
> [Nov 13th 10:33] message sent to miner (665513472934253): {"type":"job","params":{"blob":"0202bccaa7d0052c7db258c5390d37ec828ae41b40c6d3de8814166f2a5f75d132a9ae955c0fb500000000482599023359e1395f6fa83a015c282793f231e319bcac683db7d88673be64e902","job_id":"113409785064868","target":"9bc42000"}}
> [Nov 13th 10:33] message from miner (161940449965186) {"type":"submit","params":{"job_id":"897294415417127","nonce":"49521c2a","result":"0f1b72e7b1e15781c8b7f0c4cb520570ceae95eafb6157742b74764513dd0900"}}
> [Nov 13th 10:33] message sent to pool (my-monero-address): {"id":27,"method":"submit","params":{"id":"161940449965186","job_id":"897294415417127","nonce":"49521c2a","result":"0f1b72e7b1e15781c8b7f0c4cb520570ceae95eafb6157742b74764513dd0900"}}
> [Nov 13th 10:33] message from pool (my-monero-address): {"id":27,"jsonrpc":"2.0","error":{"code":-1,"message":"Invalid job id"}}
> [Nov 13th 10:33] miner conection destroyed (161940449965186)
>

**Comment by cazala** [comment]
This was a side-effect of miners/donations getting unauthenticated because they timedout. This has been fix in v2 by implementing keepalived messages
