### ISSUE TITLE
2.0.0 

### ISSUE THREAD

**Issue by matthewlilley** [cazala/coin-hive-stratum#64]
Firstly, thanks for the work @cazala 

I've been testing out 2.0.0, it's working but I'm see many of these come up in the logs. Any ideas?

couldn't send message to pool (xmrpool.eu:3333) because socket 
is not writable: [object Object]

**Comment by cazala** [comment]
mm I'll investigate, in the meantime I released a patch (2.0.1) to fix that `[object Object]`, it should be the actual message, maybe that can give some info about if a specific type of message is getting lost, or if it happens with any message.

**Comment by matthewlilley** [comment]
Thanks, I'll try again with 2.0.1 and report back.

**Comment by matthewlilley** [comment]
Logs are clean at first, then it starts appearing.

couldn't send message to pool (xmrpool.eu:3333) because socket is not writable: {"id":8,"method":"keepalived","params":{"id":"380873456830158"}}

**Comment by cazala** [comment]
is it always keepalive messages?

**Comment by matthewlilley** [comment]
Yes

**Comment by matthewlilley** [comment]
Actually, I see this one as well.

couldn't send message to pool (xmrpool.eu:3333) because socket is not writable: {"id":7,"method":"submit","params":{"job_id":"982787219528108","nonce":"f3bed820","result":"20aae38b24aed95323d530947a2a30aec0db8ef971d0ed9541f64a130a0b0100","id":"638956678821705"}}

**Comment by cazala** [comment]
which version of node are you using? also how many miners/connections do you currently have?

**Comment by cazala** [comment]
also, do you get any `socket error` or `socket closed` in the logs?

**Comment by matthewlilley** [comment]
It's running on now.sh,I'm not entirely sure what their default is. 

I only turned it on for a moment, because the hashes didn't seem correct and I saw those errors, but miners/connections will build up fast. I only put it on for a few minutes, I'll do it again and send a bin with the logs.

**Comment by matthewlilley** [comment]
Here's a small log https://file.io/pqB5f0

**Comment by matthewlilley** [comment]
{
  "miners": 228,
  "connections": 159
}

**Comment by cazala** [comment]
mmh okay, that's wrong, there shouldn't be as many connections. The default configuration is 100 miners per connection, so you should have only 3 connections for 228 miners..

**Comment by matthewlilley** [comment]
Yes, it was building up slowly at first.

https://nofile.io/f/OHrcGJvFwHq/allout.txt

**Comment by matthewlilley** [comment]
I've turned it off again now. Miners decreasing but connections still growing.

{
  "miners": 181,
  "connections": 259
}

**Comment by cazala** [comment]
There was a bug in the connection management. I fixed it and added an automatic purging mechanism to get rid of unused connections (2069379a0ace749209005d8f4fbc2ca4ca2a1ac6) I also added an exponential retry logic for sending messages to the pool. 

Those messages that you see on the logs are due to a remote disconnect (probably because of the bug in error management that was spawning too many connections). Now if the connection is dropped, the messages will be [re-queued with an exponential retry timeout](https://github.com/cazala/coin-hive-stratum/blob/master/src/Connection.ts#L119-L127), so they don't get lost during a network hiccup.

This has been released under `v2.1.0`.

**Comment by matthewlilley** [comment]
Okay, I've tested it again. The logs are clean, but it seems that miners aren't building up as they should, and hash rates are very low from what is expected. I can see the raw output in stats, and the miners array will build up to about 30-40, and then reset to 0. Is that expected?

**Comment by matthewlilley** [comment]
I have another instance which is using coinhive-party. The hashrates grow using that, quickly. I'm struggling to get above 300h/s, compared to 8000-20,000 The only reason I'm trying to switch, is because after about 24 hours, the instances die and eventually just give a 502 deployment error, even on a premium now.sh plan. I think I left a separate issue for that.

**Comment by cazala** [comment]
`coin-hive-party` uses 1 tcp connection per websocket, you can try running `coin-hive-stratum` with `--max-miners-per-connection=1` to see if that's what's causing the slowdown in hashrate.

**Comment by cazala** [comment]
the reason `coin-hive-party` dies after 24hs is probably a memory leak..

**Comment by matthewlilley** [comment]
I've set the miners per connection to one, the total miners is growing, and hashrate seems to be growing as well. Right now we're sitting at 200 miners and 1000 h/s, which is better. I'll see where we're at when we reach 1000 miners. Definitely seems to be an issue with multiple miners per connection.

**Comment by cazala** [comment]
cool, thanks for testing it out, I don't have access to large amounts of miners so this is super helpful (:

**Comment by matthewlilley** [comment]
No worries. I have some traffic I can use so it's good to figure out the scalability issues early.

Coinhive caught my attention recently, it seems like the adoption of these types of in-browser miners could be huge, another interesting thing is that it allows you to monetize traffic, which was previously next to worthless.

**Comment by cazala** [comment]
btw there was an issue with `2.1.0`, jobs didn't make it to the pool (#65) it's fixed in `2.1.2` 😇

**Comment by matthewlilley** [comment]
Looks like that was the culprit, removed that flag and miners are growing as expected, up to 100 at least. It seems to have trouble breaking that barrier at the moment. Connections keep going from 2 back to 1, it seems that active miners are possibly being lost when purging happens, maybe from the 2nd connection in this scenario?

**Comment by cazala** [comment]
if it's purging connections you should see it on the logs

**Comment by matthewlilley** [comment]
Hmm... I don't see any logs related to purging connections.

When reaching 100 miners, it's not growing further with the default max miners per connection. I switched back to 1 max miner per connection, and they started growing at the rate I'd expect again.

**Comment by matthewlilley** [comment]
It's strange, just bounces at 100+ and resets to 99, over and over it seems.

**Comment by cazala** [comment]
mm i see, there are two places when connections are purged, one is when a new miner connects and the other one is the purge interval. only the purge interval logs, so if you dont sere anything there it's probably a bug when new miners connect. I'll get rid of that since it should be enough with the purge interval.

Sent from my iPhone

On Nov 27, 2017, at 8:39 PM, Matthew Lilley <notifications@github.com<mailto:notifications@github.com>> wrote:


Hmm... I don't see any logs related to purging connections.

When reaching 100 miners, it's not growing further with the default max miners per connection. I switched back to 1 max miner per connection, and they started growing at the rate I'd expect again.

**Comment by matthewlilley** [comment]
Yes, it seems to be related to new miners connecting when it reaches the max miners per connection, it gets stuck and doesn't progress further, connections bounce between 1 and 2. 

In my case, there's many new miners connecting every second.

**Comment by cazala** [comment]
Try with version `2.1.3`, I got rid of that piece of code. Also I added a `--purge-interval` flag, if you set it to `--purge-interval=0` it will disable purging completely (just to see if the bug is in the purging interval).

**Comment by matthewlilley** [comment]
Hmm... I set --purge-interval=0, it still seems to keep resetting to 100 miners. With 1 max miner per connection, the miners grow steadily.

**Comment by matthewlilley** [comment]
I can still see purging with max miners per connection set to 1, but far fewer.

**Comment by matthewlilley** [comment]
It seems that we're losing active miners. I wasn't able to go above 100 with the default max of 100, and with max of 1, I'm close to 1000 active miners, and hashrate is growing continually reflecting that.

**Comment by cazala** [comment]
have you tried with a different value than 100? like 10? I only tried with less than 10 miners but connections grow and get purged nicely when i set a low number of miners per connection (like 3-5 miners per connection with ~10 miners)

**Comment by matthewlilley** [comment]
Yes, I've just tried but hash rate is dropping again. I've had to switch back to 1.

**Comment by cazala** [comment]
>Hmm... I set --purge-interval=0, it still seems to keep resetting to 100 miners. With 1 max miner per connection, the miners grow steadily.

Ahh sorry it has to be set like `--purge-interval=-1` in order to disable the purge interval.. setting it to 0 just falls back to the default..

>Yes, I've just tested with 10, the miners did grow a little but there's still resistance, and the hashrate was dropping. I've had to switch back to 1 per connection.

Mm this is so weird, I'm testing it with 10 miners reconnecting every second. It scales fine with 1, 2, 3, 5 miners per connection..

**Comment by vphelipe** [comment]
I have multiple miners and I can not get it to work properly. The only way to grow hashrate is by setting up 1 connection per miner. But still in a matter of minutes everything stops working. Any solution?

**Comment by matthewlilley** [comment]
Sorry for the late reply, I've just set purge interval to -1 and hash rate seems to be better. It seemed as though active miners from connection 2 were being dropped when scaling down to 1 connection.

**Comment by matthewlilley** [comment]
Maybe not, but active miners are definitely being lost somewhere.

**Comment by cazala** [comment]
@matthewilley @vphelipe have you checked #69? it looks like this config is working better for a user (this is programatically not the cli):

maxMinersPerConnection: 100,
  purgeInterval: 0,

on the cli purge interval has to be -1 in order to disable it

**Comment by matthewlilley** [comment]
Yes, I set purge interval to -1, and max miners per connection to 100, overnight a huge decrease. As soon as I set max miners per connection to 1, it bounces back to what I'd expect.
