### ISSUE TITLE
2.1.0/2.0.0 no jobs making it to pool

### ISSUE THREAD

**Issue by acalcutt** [cazala/coin-hive-stratum#65]
Hi Cazala,

When i try the new 2.x.x versions it doesn't seem like any of my jobs are making it to the pool (my hash rate drops to 0 on supportxmr.com). I switched back to 1.4.10 and it started working again. In 2.x.x it looks like jobs are being accepted from the console and client, but i'm getting nothing pool side.

I am starting with 

> coin-hive-stratum 8892 --host=pool.supportxmr.com --port=3333

(starting with 'pm2 start proxy.js --name=proxy --log-date-format="YYYY-MM-DD HH:mm"' had the same effect)

On the mining side I am using 'https://monproxy.techidiots.net', which is set to a user instead of anonymous per the instructions. 

> coinhive.CONFIG.WEBSOCKET_SHARDS = [["wss://monproxy.techidiots.net/_ws_/"]];
> var miner = coinhive.User('4B5rfHVYF7R8ag71iamrFSddbV5wAN97BG5W5VsVqPJMLML9hugBngDGwVPNZYKGPqNtoz1eJYhFWEnBCpgt4cJUG8xBPB1', 'monpoolphp');

Is there something that's changed? maybe i have to specify the user a different way in this version? version 1.4.10 is working fine, but i wanted to try out the new stats

**Comment by cazala** [comment]
You are right, I was purging the current connection 😅 this should be fixed with `2.1.2`, I just tested it with this and it's working:

```
coin-hive-stratum 8892 pool=pool.supportxmr.com port=3333
```

```html
<script src="https://coinhive.com/lib/coinhive.min.js"></script>
<script>
  CoinHive.CONFIG.WEBSOCKET_SHARDS = [["ws://localhost:8892"]];
  var miner = CoinHive.User('site-key', 'juan');
  miner.start();
</script>
```
