### ISSUE TITLE
Shares per minute not working,

### ISSUE THREAD

**Issue by CineXMike** [cazala/coin-hive-stratum#67]
Hi,
Shares per minute just doesnt show anything, Its just a black empty spot where the number should be.

Greetings,
Mike

**Comment by cazala** [comment]
<img width="382" alt="screen shot 2017-11-29 at 3 51 06 pm" src="https://user-images.githubusercontent.com/2781777/33393196-266d3830-d51d-11e7-9cb1-edbf8b682050.png">

It's working fine for me... did you get at least one share?

**Comment by cazala** [comment]
Or maybe your terminal window is too narrow for it to fit?

![expand](https://user-images.githubusercontent.com/2781777/33394038-d1e4e936-d51f-11e7-8546-a5467bd9b628.gif)

**Comment by sunk818** [comment]
Sorry, haven't kept up. If we just run coin-hive-stratum, does this appear? Or we have to use that PM2 script?

**Comment by cazala** [comment]
that's only when using pm2

**Comment by CineXMike** [comment]
Ah window is to small :)
I cant make my window any wider? any suggestions?

**Comment by cazala** [comment]
`cltr` + `-` to zoom out? `cmd` + `-` if you are in MacOS X

**Comment by cazala** [comment]
If that doesn't work I could make the label shorter

**Comment by CineXMike** [comment]
Also i have a problem with pm2,
As soon as i do pm2 monit my cpu usage goes to 97% and the console freezes.

**Comment by cazala** [comment]
mm.. what do you see in the logs? try running `pm2 logs proxy` instead of `pm2 monit`, or save the logs to a file when you start the proxy `pm2 start proxy.js --name=proxy --log-date-format="YYYY-MM-DD HH:mm" --logs=logs.txt` and then open `logs.txt`

**Comment by CineXMike** [comment]
Then nothing happens,
Its a common problem in pm2: https://github.com/Unitech/pm2/issues/2793

**Comment by cazala** [comment]
yea but what do you see in the logs if you dont use `pm2 monit` at all? Is the proxy working?

**Comment by CineXMike** [comment]
yeah it runs,
