### ISSUE TITLE
Bad hashrate with new version

### ISSUE THREAD

**Issue by hitmanex** [cazala/coin-hive-stratum#69]
Using windows server 2008.

Hash rate with previous (JS) version was 6-12KH/s with 500-2000 miners.

Hash rate with current (typescript) version is 1KH/s with 100 miners.

Normally about 500 miners connect within 10 seconds with the previous version. Now it's around 100 constantly..

something is very wrong

**Comment by hitmanex** [comment]
the issue appears to be with maxMinersPerConnection setting. Once I set this to 10000, within 20 seconds 1050 miners connected. Will give another 6 hours to see if hashrate is changed

**Comment by cazala** [comment]
Hi! thank you for all this information. So after disabling the purge interval things went back to normal? If so i'll publish a new version without it until i figure out what's breaking it.

**Comment by cazala** [comment]
@hitmanex I just released `v2.1.4` with a fix in the purge interval logic. Please if you could try it out and let me know if it's more stable. If that doesn't work, it would be really help full if you could try it with `purgeInterval: -1` (disabled) and see if that makes it stable.

**Comment by hitmanex** [comment]
It doesn't work.

miners go from  900 

to

```
"miners": 100,
  "connections": 1
```

with the purge setting..

also why is -1 disabled and not 0? i was using 0 and it worked fine

**Comment by cazala** [comment]
okay thanks, yea if you are using it programatically 0 disables it, if you are using the cli 0 falbacks to the default. i'll disable it completely then and release again, until i can debug under a heavy load amd see what's happening

**Comment by matthewlilley** [comment]
@hitmanex Have you had issues running with miners: 100? I left it on overnight with purge disabled and max miners per connection 100, and the next day hashes were down substantially. I changed this to 1 and restarted, and instantly climbed 5X.

**Comment by hitmanex** [comment]
@matthewlilley No I haven't seen much issues with miners at 100 and purge at -1.
Although I will try miners at 1 and report back.

the only issue i do see now is after a random time period (maybe half hour), there's alot of "unauthenticated" errors and I lose like 2KH (would be around 10-11KH but stays at around 9). 

I have to restart it to get it to work normally again

**Comment by procloud** [comment]
i too noticed unauths, it appears the re-auth logic is not working or absent in this version?

**Comment by hitmanex** [comment]
the reauths are causing a 20% drop in connected miners for me and a drop in KH

**Comment by hitmanex** [comment]
alright im getting unauthenticated miners after about 15 minutes which causes a significant drop in the hashrate.

i'm literally spammed with this

https://pastebin.com/raw/kwPNE2LB

**Comment by cazala** [comment]
i just published `v2.2.2`, it will the webminer connection when an error arrives from the pool to that specific miner.. so on an Unauthorized like that it will close the websocket connection, and the miner will re-authenticate. Hopefully that will help.

**Comment by hitmanex** [comment]
It's holding very steady right now with

```
  maxMinersPerConnection: 100,
  purgeInterval: -1,
```

@matthewlilley the hashrate is holding stable so far 30 minutes in with that on v2.2.2. 
@cazala you have a worker under your mining address named "proxied_contact_m5m_or_snipa"

just letting you know

**Comment by cazala** [comment]
yes I know, already talked to them, i'm setting up a proxy to route all the donation connections thru it.

**Comment by hitmanex** [comment]
there are still some unauths slipping through, but much lower than before. hashrate is holding steady

https://pastebin.com/raw/Npdccd8M

i'm content with this level of stability

**Comment by cazala** [comment]
great news (: so I should definitely get rid of the purge interval for now, and about the miners per connection, 100 is working fine then?

**Comment by cazala** [comment]
@matthewlilley could you try out v2.2.2 as well and let me know how it goes?

**Comment by hitmanex** [comment]
@cazala 

```
maxMinersPerConnection: 100,
  purgeInterval: -1,
```

is what i'm currently using. Purge interval is broken. It is holding very stable with 100 miners per connection. 

currently  "miners": 1081,
  "connections": 12

**Comment by cazala** [comment]
good. i need to do some experimentation to figure out the right amount of miners per connection. i already tried 1 connection per miner and 1 connection for all miners, both have their own issues, i believe the best is a middle ground but i still don't know what number it is. i have a proxy up and running and i need a friend of mine to start sending his miners thru it, he has around 2-4k online users so i will be able to do some debugging under a heavy load. thank you guys for testing this out and reporting issues, it's super helpful (:

**Comment by CineXMike** [comment]
I am now running aswell,
I only cant acces 127.0.0.1:8892/Stats
So i cant report stats to you since my pm2 monit freezes my whole server,

**Comment by matthewlilley** [comment]
@cazala Tested 2.2.2, with max miners 100, and purge interval disabled. Looked good at first, then hash rate plummeted by 80%, the same as before. I'm using the same settings as suggested but on the cli, --purge-interval=-1 --max-miners-per-connection=100. When I reset to --max-miners-per-connection=1, it climbs back up and remains consistent.

**Comment by matthewlilley** [comment]
All I did was start a new instance on now.sh, with those settings, and re-aliased the domain to the new instance.

**Comment by hitmanex** [comment]
survived the whole day online even after supportxmr seemed to go down at 9am EST with no issues.

very stable
