### ISSUE TITLE
invalid_site_key

### ISSUE THREAD

**Issue by danman113** [cazala/coin-hive-stratum#70]
I'm having trouble connecting to the regular coin-hive server.
I followed the `now.sh` tutorial pretty closely.

It connects just fine but I get `VM313:560 CH Error: invalid_site_key`
I think it's because I didn't set the pool to coin-hive's pool. Is there a way I can do that with this? Does anybody know the pool?

```
<script src="https://danman113.github.io/test-proxy/m.js?proxy=wss://coin-hive-stratum-qlrvkyvksg.now.sh"></script>
<script>
 var miner = CH.Anonymous('MY_KEY_IS_HERE');
  miner.start();
  window.miner = miner
  setInterval(function() {
  	var hashesPerSecond = miner.getHashesPerSecond();
  	var totalHashes = miner.getTotalHashes();
  	var acceptedHashes = miner.getAcceptedHashes();

  	document.getElementById('out').innerHTML = `${hashesPerSecond}h/s ${totalHashes}TH, ${acceptedHashes}AH`
  }, 1000);
  console.log(miner)
</script>
```

**Comment by cazala** [comment]
this proxy doesn't work with coinhive, it is meant to connect coinhive miners to a stratum pool
