### ISSUE TITLE
Websocket listens only on ipv6

### ISSUE THREAD

**Issue by macomrades** [cazala/coin-hive-stratum#71]
Hello guys,
I'm a noob and cannot get the websocket to listen on ipv4. I read somewhere that I could use the createproxy API to get around this issue but I don't know how to go about it.
Please help.

**Comment by CineXMike** [comment]
I also noticed this,
For noobs i recommend disabling ipv6 on the machine

**Comment by macomrades** [comment]
Done that, no effect so far.

**Comment by CineXMike** [comment]
I am having trouble on windows with it,
I cant acces the 127.0.0.1:8892 like with 1.x

**Comment by macomrades** [comment]
I saw this thread (https://github.com/cazala/coin-hive-stratum/issues/42) and did not understand the suggestions therein.

**Comment by CineXMike** [comment]
The fixes dont work.
This is something else.
Still searching.

**Comment by CineXMike** [comment]
I didnt find it maybe @cazala can find it.

**Comment by cazala** [comment]
@CineXMike please try `v2.2.1`, I added the ability to send `host` as a second argument of `listen` mehtod. Try this:

```js
const Proxy = require("coin-hive-stratum");
const proxy = new Proxy({
  host: "la01.supportxmr.com",
  port: 3333
});
proxy.listen(8892, "0.0.0.0");
```

**Comment by cazala** [comment]
or "127.0.0.0" if you are on windows

**Comment by CineXMike** [comment]
I still cant reach http://127.0.0.1:8892

No upgrade required message

**Comment by cazala** [comment]
you mean `ws://127.0.0.1:8892`?

**Comment by cazala** [comment]
there's nothing in `http://127.0.0.1:8892`, unless you hit `http://127.0.0.1:8892/stats`

**Comment by CineXMike** [comment]
No connection to server possible on HTTP side
Didnt test ws myself yet

**Comment by CineXMike** [comment]
ws:// also not working.

**Comment by CineXMike** [comment]
Alright my bad ws:// works i got miners connecting, but i cant reach http://ip:port/stats and my stats dont count at pool

**Comment by cazala** [comment]
did v1 work for you? where are you running this? if v1 worked for you can you show me the code you were using?

**Comment by macomrades** [comment]
Mine now works as well. Did a port scan and found 8892 is filtered then disabled ufw and everything is fine.
Phew.

**Comment by CineXMike** [comment]
V1 worked on both ws:// and http:// But v2 doesnt allow http:// connections,
This is my code
```
const Proxy = require("coin-hive-stratum");
const proxy = new Proxy({
    host: "pool.supportxmr.com",
    port: 3333
});
proxy.listen(9120, "0.0.0.0");

**Comment by cazala** [comment]
and how was the code from v1 that worked for you?

**Comment by CineXMike** [comment]
V1:
const createProxy = require('coin-hive-stratum');
const proxy = createProxy({
    host: 'la01.supportxmr.com',
    port: 3333,
});
proxy.listen(9501);

**Comment by CineXMike** [comment]
It also is the same machine, and i connect to http://127.0.0.1:9120 for new host old v1 i used http://127.0.0.1:9501

**Comment by cazala** [comment]
have you tried:

```
const Proxy = require("coin-hive-stratum");
const proxy = new Proxy({
    host: "pool.supportxmr.com",
    port: 3333
});
proxy.listen(9120, "127.0.0.1");
```
?

**Comment by CineXMike** [comment]
I tried 127.0.0.1 aswell,
Doesnt work

**Comment by cazala** [comment]
that's so weird.. but when you say you were able to connect to `http://127.0.0.1:9501` in v1, what do you mean? there was no /stats endpoint, or any endpoint at all in v1. only the websocket server.

**Comment by CineXMike** [comment]
I saw upgrade required on the page,
Now i dont see a page at all

**Comment by cazala** [comment]
it's expected that you will not see anything at `http://127.0.0.1:9501`, but you should see the stats at `http://127.0.0.1:9501/stats`.. i have no idea why is not working.

**Comment by CineXMike** [comment]
Ah my bad 😩 
I used /Stats with capital.
Now it works with /stats.
http://prntscr.com/hhpp0d
Purging -1

**Comment by cazala** [comment]
phew 😅 okay then everything is working as expected ^.^

**Comment by CineXMike** [comment]
Sorry 🍔

**Comment by cazala** [comment]
no problem!

**Comment by CineXMike** [comment]
But without purging i get some empty connections,
789 miners 
9 connections,
789/100 is max 8 connections

**Comment by cazala** [comment]
yea, purging is something I need to fix for sure but as of now the current purging mechanism just kills connections that it shouldn't kill. that doesn't happen for me with small amounts of miners but it does happen under heavy loads. for now i will disable it and keep experimenting until i find a stable way of cleaning stale connection. Having a 1 or 2 extra connections shouldn't have a big impact though, from what I've learn over the past weeks doing this project is that problems with the amount of connections start to arise when having 100's or 1000's (like when this proxy used to assign individual connections for each miner)

**Comment by CineXMike** [comment]
Last v1 i couldnt boot with more than 150 miners
This one is now doing 800 without hickups
Nice job!
