### ISSUE TITLE
possible to get more Metrics in stats?

### ISSUE THREAD

**Issue by acalcutt** [cazala/coin-hive-stratum#72]
I was thinking about making some graphs thats read from the stats page and was wondering if Is it possible to get 'Shares' and 'Shares per minute' into the stats page or does this get calculated in pm2? I'm guessing i would need to add it into Proxy.ts/getStats but i'm not seeing where those value are calculated.

Also related but not quite the same I was wondering if theres a way to included miner addresses connected as part of stats or on its own stats page.

**Comment by cazala** [comment]
the metrics are computed by pmx (pm2 metrics) they can be found in src/Metrcis.ts

I will improve soon the rest api, many people have asked for the ability to get shares by user as coinhive does

**Comment by acalcutt** [comment]
Thanks. I did see the Metrics.ts but I didn't see any calculations in there so i figured it was pm2 doing the heavy lifting. Just figured I'd ask, I know I like feature requests on my own code :-)

More stats on the miners would be nice. I was just wondering what users are connected in general. With 1.x I could somewhat see who was connecting in the logs, but with the cleaner 2.x logs its hard to tell.

Great work so far btw. the coinhive concept is a good one, but they are charging way to much at 30%. I was also looking at jazecminer (https://github.com/mtve/yazecminer) which is similar in concept but for equihash, but the miner only does one core and i haven't gotten it to do more yet. this one is nice though because it also have the source code for the miner.

**Comment by cazala** [comment]
I just added two more endpoints `/miners` and `/connections` to show some more information. I also added basic auth to protect the endpoints: https://github.com/cazala/coin-hive-stratum#stats it is released in version 2.5.0

**Comment by letlet** [comment]
@cazala Hi,  I have used CHS as my proxy server to mine at supportxmr.com and get much more XMR than at Coinhive,thank u for your great job!.  How is the ability to get shares by user as coinhive does going? Really need this to make the webpage mining more efficient.
