### ISSUE TITLE
miners discontected

### ISSUE THREAD

**Issue by vsystech** [cazala/coin-hive-stratum#73]
Dear developer, i have a problem. when connected miners i looking in the log.

Miners connected ....
Miners discontected.... 

What is the problem ? i use supportxmr.com

http://prntscr.com/hhg8q5

**Comment by vsystech** [comment]
Some time(s), when connected the miners. not start hashing. 

Hashes/s : 0
Total Hashes/s : 0
Total Accept : 0

**Comment by cazala** [comment]
when a user changes from a page to another the ws connection is closed, and then the miner reconnects once the new page is loaded
