### ISSUE TITLE
Electroneum network issue

### ISSUE THREAD

**Issue by PiTi2k5** [cazala/coin-hive-stratum#75]
Hello and thanks for your hard work :)

I use your proxy and coinhive webminer with a stratum Electroneum pool. But i can only use the old version below 2.0.0

Usage with old version proxy and pm2:
Users can put their ETN address and start mining on pool.electroneum.space it runs fine...
Issue --> miner do a auto restart random at every 10-30k total hashes and 30+ accepted hashes
(But is it not a big problem because of auto restart and mining again)

Usage with new version proxy and pm2:
Users can put their ETN address and start mining on pool.electroneum.space it runs fine...
Issue --> random at every 10-30k total hashes and 30+ accepted hashes, the miner do only increase total hashes, not accepted hashes
(I think the miners a disconnected but it's strange because of increase of total hashes and use of CPU power)

Sorry for my bad english :> 

greets from germany

update: i tested v2.3.0 same issue

**Comment by cazala** [comment]
So you are connecting the pool to an electroneum pool? I never tried that before.. i'll try it and and get back to you.

**Comment by PiTi2k5** [comment]
Yes it runs with your proxy and coinhive javascript miner, except the proxy version issue. Electroneum has the same algo (Cryptonight) as Monero.

**Comment by cazala** [comment]
i need to make some tests but if it was working with v1 i can make it work with v2

Sent from my iPhone

On Dec 1, 2017, at 3:45 PM, PiTi2k5 <notifications@github.com<mailto:notifications@github.com>> wrote:


Yes it runs with your proxy and coinhive javascript miner, except the proxy version issue. Electroneum has the same algo (Cryptonight) as Monero.

**Comment by pinkflozd** [comment]
As i found out versions above 2.0 don't work with cryptonote-universal-pool (most ETN pools use it).
Most monero pools use nodejs-pool and it works on ETN pools using nodejs-pool (only a few of them use it)
Version 1 worked fine on cryptonote-universal-pool

**Comment by cazala** [comment]
I can mine perfectly fine on `uspool.electroneum.com:3333` using `v2.3.3`

<img width="741" alt="screen shot 2017-12-03 at 4 14 25 am" src="https://user-images.githubusercontent.com/2781777/33523248-98d73072-d7e0-11e7-8e8c-449c80f37e12.png">

**Comment by pinkflozd** [comment]
i can confirm that versions 2.3+ work on cryptonote-universal-pool

**Comment by PiTi2k5** [comment]
And on long term? Proxy runs fine the first 30k total hashes and around 40 accepted hashes but then the submit stops and only the total hashes increase.

Can't test the new Proxy v2.3.5
It don't build proxy.ts / proxy.js it's not there

**Comment by cazala** [comment]
yep, I screwed up with my `.gitignore` and left the `build/Proxy.js` out of the package 😅 it's fixed now, try version `v2.4.5`

**Comment by PiTi2k5** [comment]
Thanks for your hard work. I test it now 2.4.5
It runs perfect. All issues are fixed.
Runs without auto restart issue and total hashes / accepted hashes always increase.
Good job man

**Comment by PiTi2k5** [comment]
After more tests, same issue with accepted hashes :/
Tested Pools: eupool.electroneum.com and pool.electroneum.space

I dont know why it runs perfect on first test.

**Comment by cazala** [comment]
mm this is just a wild guess, but what if they have set dynamic difficulty? some pools have starting difficulty and then they adjust it according to you hashrate (if you send too many hashes then they increase the difficulty of the jobs they send you).

You can confirm this by opening the Network tab, refreshing the page, and looking at the WS frames:

<img width="1077" alt="diff" src="https://user-images.githubusercontent.com/2781777/33527675-8b68c146-d833-11e7-8bd5-392f3b8f22d3.png">

If you look at the `"job"` messages, they have a param `target` which is the difficulty of that job. If you see this number change over time probably the pool is adjusting the difficulty for your miner according to your hashrate.

**Comment by PiTi2k5** [comment]
Yes its dynamic diff pool but i run a test, now it stopped on accepted hashes 32 and total hashes rise on 100k+. In 15 min he should find a single accept hash

**Comment by PiTi2k5** [comment]
<img width="398" alt="unbenannt" src="https://user-images.githubusercontent.com/15856741/33527859-fce38b8e-d857-11e7-8634-67a0f9c55c77.PNG">
<img width="418" alt="unbenannt2" src="https://user-images.githubusercontent.com/15856741/33527860-fcfb73d4-d857-11e7-81ed-7d567c07643c.PNG">

**Comment by PiTi2k5** [comment]
Shares not increase

**Comment by PiTi2k5** [comment]
<img width="394" alt="unbenannt3" src="https://user-images.githubusercontent.com/15856741/33527872-47b852a2-d858-11e7-9eb9-df15977fa685.PNG">

**Comment by cazala** [comment]
so it starts working fine and it stops after a while.. I'll run some tests and see if i can figure out what it is

**Comment by cazala** [comment]
mm by looking at the logs tho it seems like it's always submitting the same two jobs? maybe that's why the pool is not responding with an `{ "status": "OK" }` ? cos that's what it needs to happen for it to log the accepted shares message.

**Comment by PiTi2k5** [comment]
I think it is the same issue point with old proxy version.
Old version do a mining auto restart
New version stops accept hashes on that Old version proxy issue point

**Comment by PiTi2k5** [comment]
The break comes with invalid job id on old proxy version

**Comment by cazala** [comment]
you are right. I checked the code, in this version the `invalid job id` is not being handled (it's a bug) it should be emitted as any other error, and reset the connection. I'll publish a new version soon with this fixed.

**Comment by cazala** [comment]
i still don't know why you start getting that invalid job id after a while.. but it should be handled gracefully, reconnect and reauth the miner.

**Comment by PiTi2k5** [comment]
http://a-calc.de/miner/startapp.html

**Comment by PiTi2k5** [comment]
Maybe a bug in http://www.a-calc.de/miner/scripts/proxy.js?v1 in that file i have the coinhive miner function. On my tests with <script src="https://coinhive.com/lib/coinhive.min.js"></script> the antivirus do a alarm

**Comment by cazala** [comment]
now errors in jub submissions should be emitted, making the miners to reconnect (64c63b2bcc9b094af17a0f9816c4056beb3bfe92) please try v2.5.0 and let me know if it does the trick

**Comment by PiTi2k5** [comment]
On v2.5.0 auto restart works fine like old proxy version

<img width="459" alt="unbenannt5" src="https://user-images.githubusercontent.com/15856741/33528511-ca0c694c-d861-11e7-874b-f50b42b0e3cc.PNG">

**Comment by PiTi2k5** [comment]
<img width="522" alt="unbenannt6" src="https://user-images.githubusercontent.com/15856741/33528517-f501f824-d861-11e7-9724-03bf7f411779.PNG">

**Comment by cazala** [comment]
awesome :D

**Comment by hitmanex** [comment]
I tried mining for eupool.electroneum.com. My monero hashrate is usually around 10KH. for electroneum it was around 1.6KH. I tried another pool and it was even lower there at around 800H/s.

Shouldn't the hashrate be around 10kh like moneros?

**Comment by hitmanex** [comment]
@cazala i'm getting alot of 

```
pool connection error (b43dc364-4378-4d2e-abdb-b941f6f906fe): {"code":-1,"messag
e":"Invalid job id"}
```

errors on electroneum.uax.io

https://pastebin.com/raw/B9BNAQS3

**Comment by PiTi2k5** [comment]
Yes it is normal on various ETN Pools with cryptonote-universal-pool, but the miners restart immediately. I run this proxy since 2 weeks and i get fullspeed and runs perfect

**Comment by hitmanex** [comment]
@PiTi2k5 on supportxmr i get around 9KH normally at this time and on electroneum i'm getting only about 7.9KH
