### ISSUE TITLE
Unable to run with PM2

### ISSUE THREAD

**Issue by adamdupuis** [cazala/coin-hive-stratum#76]
Anyone else having issues with this?

After starting with PM2 and running monit I see the following:

[ 0] proxy      Mem:  xx proxy >     at Module.require (module.js:579:17)     x
x                      xx proxy >     at require (internal/module.js:11:18)    x
x                      xx proxy >     at Object.<anonymous> (/proxy.js:1:77)   x
x                      xx proxy >     at Module._compile (module.js:635:30)    x
x                      xx proxy >     at Object.Module._extensions..js         x
x                      xx (module.js:646:10)                                   x
x                      xx proxy >     at Module.load (module.js:554:32)        x
x                      xx proxy >     at tryModuleLoad (module.js:497:12)      x
x                      xx proxy >     at Function.Module._load (module.js:489  x
x                      xx :3)                                                  x
x                      xx PM2 > App [proxy] with id [0] and pid [28940],       x
x                      xx exited with code [1] via signal [SIGINT]             x
x                      xx PM2 > Script /proxy.js had too many unstable         x
x                      xx restarts (16). Stopped. "errored"                    x
mqqqqqqqqqqqqqqqqqqqqqqjmqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqj
lq Custom metrics     qklq Metadata qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqk
x (http://bit.ly/code- xx App Name              proxy                          x
x metrics)             xx Restarts              107                            x
x                      xx Uptime                0                              x
x                      xx Script path           /proxy.js                      x
mqqqqqqqqqqqqqqqqqqqqqqjmqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqj

**Comment by CineXMike** [comment]
Please post outcome of pm2 logs proxy

**Comment by adamdupuis** [comment]
[TAILING] Tailing last 15 lines for [proxy] process (change the value with --lines option)
/root/.pm2/logs/proxy-out-0.log last 15 lines:
/root/.pm2/logs/proxy-error-0.log last 15 lines:
0|proxy    |     at Object.Module._extensions..js (module.js:646:10)
0|proxy    |     at Module.load (module.js:554:32)
0|proxy    |     at tryModuleLoad (module.js:497:12)
0|proxy    |     at Function.Module._load (module.js:489:3)
0|proxy    | 2017-12-01 17:36: Error: Cannot find module 'coin-hive-stratum'
0|proxy    |     at Function.Module._resolveFilename (module.js:536:15)
0|proxy    |     at Function.Module._load (module.js:466:25)
0|proxy    |     at Module.require (module.js:579:17)
0|proxy    |     at require (internal/module.js:11:18)
0|proxy    |     at Object.<anonymous> (/proxy.js:1:77)
0|proxy    |     at Module._compile (module.js:635:30)
0|proxy    |     at Object.Module._extensions..js (module.js:646:10)
0|proxy    |     at Module.load (module.js:554:32)
0|proxy    |     at tryModuleLoad (module.js:497:12)
0|proxy    |     at Function.Module._load (module.js:489:3)

**Comment by adamdupuis** [comment]
In the log file itself I get the error "Cannot find module 'coin-hive-stratum'". I have no issues running the app itself though.

**Comment by CineXMike** [comment]
Run npm install coin-hive-stratum inside the folder where script.js is.
Then try starting it.

**Comment by CineXMike** [comment]
Working?

**Comment by adamdupuis** [comment]
Yes, that seems to have solved it. Thanks!
