### ISSUE TITLE
Feature Request - option for different port for /stats

### ISSUE THREAD

**Issue by procloud** [cazala/coin-hive-stratum#77]
for security and privacy reasons it would be great to be able to run /stats and future api requests on another port

**Comment by CineXMike** [comment]
We Will look for different ways to make this secure!

**Comment by hitmanex** [comment]
you can just edit the proxy file and change it from /stats to /whatever. thats what i did

**Comment by CineXMike** [comment]
@hitmanex That is the best solution for now!

**Comment by cazala** [comment]
Hi @procloud @hitmanex @CineXMike I added the ability to protect the stats endpoints with basic auth: https://github.com/cazala/coin-hive-stratum#stats

**Comment by cazala** [comment]
it is available in `v2.5.0`
