### ISSUE TITLE
2.3.0 - Shares are submitting but no results on pool side

### ISSUE THREAD

**Issue by procloud** [cazala/coin-hive-stratum#78]
I am still testing one low hash web miner.

No shares for some time and then shares start adding up (and repeating?) 

proxy > 2017-12-02 21:10: job submitted (a387a4ff-8cf1-48a8-9c65-3c325397dd80): Ee9fGJdv1/ah3wS3cKoW9hMpW4H7
proxy > 2017-12-02 21:10: shares accepted (a387a4ff-8cf1-48a8-9c65-3c325397dd80): 2753
proxy > 2017-12-02 21:10: job submitted (a387a4ff-8cf1-48a8-9c65-3c325397dd80): Ee9fGJdv1/ah3wS3cKoW9hMpW4H7
proxy > 2017-12-02 21:10: shares accepted (a387a4ff-8cf1-48a8-9c65-3c325397dd80): 2754
proxy > 2017-12-02 21:10: job submitted (a387a4ff-8cf1-48a8-9c65-3c325397dd80): Ee9fGJdv1/ah3wS3cKoW9hMpW4H7
proxy > 2017-12-02 21:10: shares accepted (a387a4ff-8cf1-48a8-9c65-3c325397dd80): 2755

But nothing shows up on the pool side.

I tried Setting the donation level to 0.00 and even changed your donation settings to use mine (on nyc01.supportxmr.com port 8080 (for low diff)) with the same results.

I dont see the worker name ever showing up on the pool dashboard.

**Comment by CineXMike** [comment]
Set pool to pool.supportxmr.com:3333
Make sure you put right monero adress in CoinHive.Anonymous().
Try restarting it.

**Comment by procloud** [comment]
im overiding the address in the config because i dont want my monero addy out in the wild.

trying a different supportxmr address appears to have fixed the issue.

looks like it was pool side.

thanks for looking out
