### ISSUE TITLE
Can you add nicehash support?

### ISSUE THREAD

**Issue by Vanzent** [cazala/coin-hive-stratum#86]
Can you add nicehash support?

**Comment by cazala** [comment]
that has to be supported on the miner, not the proxy: https://github.com/cazala/coin-hive-stratum/issues/50#issuecomment-341643978

**Comment by Vanzent** [comment]
You did the program specifically for the CH? CH does not support nicehash, there is no such function. But it would be very easy to do in CHP. Why not?

**Comment by sunk818** [comment]
If it is so easy why don't you make the code change and submit it?

**Comment by cazala** [comment]
Sorry I didn't get waht you said, what's CHP?
