### ISSUE TITLE
Electroneum support?

### ISSUE THREAD

**Issue by soporhs** [cazala/coin-hive-stratum#87]
This is not an issue, but rather a feature suggestion.
So as we know, mining ETN is more profitable than XMR now, and since it is Cryptonight and the mining process is pretty much the same, I decided to try it.
However, a problem was encountered. 

`soporhs@soporpi:~/proxy_etn $ node proxy.js`

> coin-hive-stratum v2.5.9
listening on port 9090
host: pool.electroneum.space
port: 1111
pass: x
miner connected (51c20058-017b-4d59-9c77-377425f9cb2a)
socket error (pool.electroneum.space:1111) read ECONNRESET
connection error (pool.electroneum.space:1111): read ECONNRESET
socket closed (pool.electroneum.space:1111)
connection closed (pool.electroneum.space:1111)
miner started (51c20058-017b-4d59-9c77-377425f9cb2a)
miner authenticated (51c20058-017b-4d59-9c77-377425f9cb2a): 445386063307523
job arrived (51c20058-017b-4d59-9c77-377425f9cb2a): 508602871140465`

Nothing happens after that. 
This does not seem like a serious problem. Still, it is interesting to know if this can be easily fixed.

**Comment by cazala** [comment]
I have to check that pool, but `uspool.electroneum.com` was working last time I checked

**Comment by cazala** [comment]
I notice is kinda slow (takes a while to respond the authentication and job submissions) but it's working:

**index.html**

```html
<script src="https://coinhive.com/lib/coinhive.min.js"></script>
<script>
  CoinHive.CONFIG.WEBSOCKET_SHARDS = [["ws://localhost:8892"]];
  var miner = CoinHive.Anonymous('etn-address');
  miner.start();
</script>
```

**proxy.js**

```js
const Proxy = require("coin-hive-stratum");
const proxy = new Proxy({
  host: "pool.electroneum.space",
  port: 1111
});
proxy.listen(8892);
```

Output
```
$ node proxy.js
coin-hive-stratum v2.5.10
listening on port 8892
host: pool.electroneum.space
port: 1111
pass: x
miner connected (c33102e2-1cfb-4f78-bc10-ed0eff85df1a)
miner started (c33102e2-1cfb-4f78-bc10-ed0eff85df1a)
miner connection closed (c33102e2-1cfb-4f78-bc10-ed0eff85df1a)
miner disconnected (c33102e2-1cfb-4f78-bc10-ed0eff85df1a)
miner connected (e7946794-f44f-4db3-83a5-d42e9f708b80)
miner started (e7946794-f44f-4db3-83a5-d42e9f708b80)
miner authenticated (e7946794-f44f-4db3-83a5-d42e9f708b80): 201622365461662
job arrived (e7946794-f44f-4db3-83a5-d42e9f708b80): 303182742977514
job submitted (e7946794-f44f-4db3-83a5-d42e9f708b80): 303182742977514
shares accepted (e7946794-f44f-4db3-83a5-d42e9f708b80): 1
job submitted (e7946794-f44f-4db3-83a5-d42e9f708b80): 303182742977514
shares accepted (e7946794-f44f-4db3-83a5-d42e9f708b80): 2
```

**Comment by hitmanex** [comment]
can you check this running a bit longer. my hashes drop from 10KH to 300H on electroneum..tried 3 different pools

**Comment by soporhs** [comment]
I checked other pools, everything is working.
