### ISSUE TITLE
I Receive Error message !

### ISSUE THREAD

**Issue by OntChan** [cazala/coin-hive-stratum#88]
Now Create ok.

Alias Ok.

Fork and Rename Ok.

But, 

code | 404
-- | --
error | "Not Found"

Help me Please.

Thx

**Comment by cazala** [comment]
You client can be found here, `https://ontchan.github.io/my-proxy/m.js`, you need to pass your proxy as a parameter and the pool.

I don't know the url of your proxy in now, but let's say is `ontchan-proxy.now.sh`, your url would be like:

```
https://ontchan.github.io/my-proxy/m.js?proxy=wss://ontchan-proxy.now.sh?pool=pool.supportxmr.com:3333
```

And it would be used like this:

```
<script src="https://ontchan.github.io/my-proxy/m.js?proxy=wss://ontchan-proxy.now.sh?pool=pool.supportxmr.com:3333"></script>
<script>
  var miner = CH.Anonymous('SITE_KEY');
  miner.start();
</script>
```

Where are you getting that 404?

**Comment by cazala** [comment]
@OntChan do you still get a 404?

**Comment by OntChan** [comment]
I configured a proxy in a vps and it is working ok

I tested with the supportxmr.com pool and a monero address. Perfect.

But, when I was trying with the coinhive parameters using the created proxy, I get this message in the PM2 Dashboard.

 invalid_site_key

My parameters:

<script src = "https://ontchan.github.io/my-proxy/m.js?proxy=ws://my.ip"> </ script>
<script>
var miner = CH.Anonymous ('mykey');
  miner.start ();
</ script>

I checked more than one key and it is correct.

Any suggestion? Thank you

**Comment by cazala** [comment]
This proxy is to connect CoinHive's miner to a different pool, it doesn't work mining on `coinhive.com`. 

The error you are seeing is because you are passing a CoinHive Site Key instead of a Monero address.

**Comment by cazala** [comment]
There might be support for mining on coinhive.com in the near future, but currently is not possible.
