### ISSUE TITLE
Huge hash rate difference between

### ISSUE THREAD

**Issue by pixeleate** [cazala/coin-hive-stratum#90]
First of all, @cazala thanks for your awesome work 

Until some days ago I was using the CoinHive script without any modifications and I was seeing 25 - 30 H/s per miner on their page, then I decided to use your proxy following the instructions to deploy it to ‘now.sh’ but using this approach I’m getting 6 - 8 H/s per miner, is that the expected behavior? Is there a way to solve this issue?

I’m using this repo without modifications, I have only put my wallet address 

Best regards

**Comment by cazala** [comment]
what is the hashrate that you where getting in CoinHive's dashboard and what is the hashrate that you are getting in the pool you are mining?

**Comment by cazala** [comment]
I mean, total hashrate, and how many online miners do you have? Maybe the free now.sh instance can't cope with the traffic

**Comment by pixeleate** [comment]
Total hashrate on the coinhive dashboard 6000H/s.

Using supportxmr or monerohash along with the proxy I'm getting not more that 1800H/s

Yeah, I was thinking the same about the free now.sh, I will trying paying to see the difference.

**Comment by cazala** [comment]
That's strange tho, I've talked to users that are also around the same numbers in CoinHive that are using this proxy without problems. But I think none of them is using now.sh, they host the proxies on VPS or dedicated servers, maybe that's why.

**Comment by pixeleate** [comment]
Let me try that today and I'll update the issue with my results

**Comment by PiTi2k5** [comment]
Hello, i can confirm that the proxy runs perfect on a VPS with fullspeed on hashrate. I run 2 proxy instances Electroneum and Monero since Proxy V1.

**Comment by cazala** [comment]
@pixeleate are you loading the miner from coinhive or from github pages?

**Comment by pixeleate** [comment]
@PiTi2k5 those are good news, could you tell me your VPS provider? is that amount of RAM needed? I'm planning to use digitalocean

@cazala I'm loading the file from github pages

**Comment by PiTi2k5** [comment]
https://www.netcup.de/bestellen/produkt.php?produkt=1571 i use that rootserver, no so much ram is not needed. I run many various projects and websites ;) i like her internet connection and ssd performance

**Comment by cazala** [comment]
@pixeleate if you are planning to use DO yesterday I added a guide for it to the wiki, some parts lf it might be useful: https://github.com/cazala/coin-hive-stratum/wiki/Deploy-to-Digital-Ocean

**Comment by pixeleate** [comment]
@cazala thanks about that, I have some other apps running on DO, everything is working fine so far, I'm using `ws://`, but I'm planning to upgrade to a secure connection later this week, I'm seeing only a small difference between CoinHive and the proxy, no more than 100H/s that's not a big deal, I can live with that.

BTW your DO guide looks very good, good job.

You can close this issue if you want, thanks again, I'm gonna send you few Monero coins later this week 🍺

**Comment by cazala** [comment]
I'm glad to help ^.^

**Comment by sunk818** [comment]
For Digital Ocean, try entering promo code LOWENDBOX $15/credit. If that doesn't work try DROPLET10 for $10/credit. @cazala if you have a Digital Ocean account, you should include your referral link so people can get $10/credit to sign up. So, that ends up being $25 credit in total. (Make sure you use a clean default browser e.g. firefox portable or google chrome portable so all the referral tracking actually works)

**Comment by cazala** [comment]
I already had a DigitalOcean account, but I added the promo codes and my referral link to the wiki, thanks for the tip!
