### ISSUE TITLE
Trouble with Deploy to now.sh and GitHub Pages

### ISSUE THREAD

**Issue by razza-guhl** [cazala/coin-hive-stratum#94]
Hi,

First of all, thank you for your good work here. I'm new to all of this, so sorry for my propably dumb question.

I tried to setup a proxy on now.sh like described in your Wiki-article [Deploy to now.sh and GitHub Pages](https://github.com/cazala/coin-hive-stratum/wiki/Deploy-to-now.sh-and-GitHub-Pages)

I have the problem that there is no "m.js"-file on my github page, that is mentioned in this article:
`https://<YOUR-GITHUB-USERNAME>.github.io/my-proxy/m.js`

I forked the repo "https://github.com/cazala/coin-hive-stratum" for the github page.

Another thing is, how is it possible to change the global variable _CoinHive_ to _CH_ like shown here:
```
<script src="https://cazala.github.io/my-proxy/m.js?proxy=wss://my-proxy.now.sh?pool=pool.supportxmr.com:3333"></script>
<script>
  var miner = CH.Anonymous('SITE_KEY');
  miner.start();
</script>
```

Thanks for helping out!

**Comment by cazala** [comment]
I think it has to do with the fact that you already have a main github page: `https://razza-guhl.github.io` so maybe when you do `razza-guhl.github.io/coin-hive-stratum/m.js` is looking for the file in this repo: https://github.com/razza-guhl/razza-guhl.github.io

**Comment by razza-guhl** [comment]
Thanks @cazala . It's working now.

I cannot say what was exactly the issue. I deleted the main-repo "razza-guhl.github.io" => did not work. 
Then, in the repo-settings for "coin-hive-stratum" under "GitHub Pages" i switched source to "master branch", saved, and then back to "gh-pages branch", saved => works.

Awesome work!

**Comment by cazala** [comment]
I'm glad to help (:
