### ISSUE TITLE
How to connect to the pool?

### ISSUE THREAD

**Issue by avnerbarr** [cazala/coin-hive-stratum#98]
I've followed the instructions here: https://github.com/cazala/coin-hive-stratum/wiki/Deploy-to-now.sh-and-GitHub-Pages

I've forked the assets repo, and I've created a now.sh instance.

But I don't understand what is supposed to happen in this part of the instructions:

```
<script src="https://avnerbarr.github.io/yonitost-proxy/m.js?proxy=wss://yonitost-proxy.now.sh?pool=HOST:PORT"></script> <<<< Which pool should I be using?
 <script> var miner = CH.Anonymous('SITE_KEY'); <<< What is the SITE_KEY? 
miner.start(); 
</script>
```

Thanks!

**Comment by mport88** [comment]
Perhaps a typo - SITE_KEY -> your monero wallet

**Comment by cazala** [comment]
Yep, the wiki page was wrong it should've said `MONERO_WALLET_ADDRESS` (I corrected it already).

If you don't have a monero wallet, you can get one from [mymonero.com](https://mymonero.com/)

You can use the pool `pool.supportxmr.com:3333` and check your stats a [supportxmr.com](https://supportxmr.com)
