### ISSUE TITLE
How can I use multiple web sockets at the same time?

### ISSUE THREAD

**Issue by adamdupuis** [cazala/coin-hive-stratum#99]
I'd like to use wss:// when the site is https:// and ws:// when it is http://.

Currently when I try to connect to my proxy via wss:// on a non-https server I get the error "can’t establish a connection to the server ws://...". Or maybe there a better way to do this or a method to make the proxy accept both?

**Comment by cazala** [comment]
Would this work?

```
<script src="https://coinhive.com/lib/coinhive.min.js"></script>
<script>
  // Configure CoinHive to point to your proxy
  CoinHive.CONFIG.WEBSOCKET_SHARDS = location.protocol === 'https:' ? [["wss://localhost:8892"]] : ["ws://localhost:8892"]];

  // Start miner
  var miner = CoinHive.Anonymous('your-monero-address');
  miner.start();

</script>
```

**Comment by adamdupuis** [comment]
Well my issue right now is I can't even connect to ws://localhost:8892 when not on https. I'm thinking this is due to including the SSL certificates in the startup of coin-hive-stratum.

**Comment by cazala** [comment]
from `https://` you can connect to `wss://` only.

from `http://` you should be able to connect to both `ws://` and `wss://`.

**Comment by cazala** [comment]
Did you make sure your certs are right?

**Comment by adamdupuis** [comment]
Well it works on https with wss perfectly fine, but not without SSL.

**Comment by cazala** [comment]
Are you passing your certs when instantiating your proxy? If so, the proxy will not accept requests from `http://`, because it will use an HTTPS server.

**Comment by adamdupuis** [comment]
Yes in proxy.js I specify the certificate and key:
`  key: require("fs").readFileSync("key.pem"),
  cert: require("fs").readFileSync("cert.pem")`

What should I be doing instead?

**Comment by cazala** [comment]
Mmm I just set up an HTTP server and a proxy using a secure connection and it's working.

**test.js**

```js

// HTTP static server
const express = require("express");
var app = express();
app.use("/static", express.static("static"));
const staticServer = require("http").createServer(app);
staticServer.listen(8081);

// Proxy (using HTTPS server)

const Proxy = require("coin-hive-stratum");
const proxy = new Proxy({
  dynamicPool: true,
  key: require("fs").readFileSync("../ssl/localhost.key"),
  cert: require("fs").readFileSync("../ssl/localhost.crt")
});
proxy.listen(8892);
```

I have a `/static` directory with `m.js`, `a.js`, `a.mem`, `c.wasm` and an `index.html` that looks like this:

**index.html**

```html
<script src="http://localhost:8081/static/m.js?proxy=wss://localhost:8892?pool=nyc01.supportxmr.com:3333"></script>
<script>
  var miner = CH.Anonymous('monero-address');
  miner.start();
</script>
```

And when I go to `http://localhost:8081/static` the miner starts just fine (notice it is `http://`):

**WS Request (over wss://)**

```
Request URL:wss://localhost:8892/?pool=nyc01.supportxmr.com:3333
Request Method:GET
Status Code:101 Switching Protocols
```

**Proxy (using secure connection)**

```
coin-hive-stratum v2.6.4
listening on port 8892, using a secure connection
miner connected (287b0b40-0ff3-476f-b2a9-4d7cec190968)
miner started (287b0b40-0ff3-476f-b2a9-4d7cec190968)
miner authenticated (287b0b40-0ff3-476f-b2a9-4d7cec190968): f5bf921f-4b03-4cf8-a5ca-256f3f5d4724
job arrived (287b0b40-0ff3-476f-b2a9-4d7cec190968): aRx9t2dCY5pLRUandNn9+gLepvxS
job submitted (287b0b40-0ff3-476f-b2a9-4d7cec190968): aRx9t2dCY5pLRUandNn9+gLepvxS
shares accepted (287b0b40-0ff3-476f-b2a9-4d7cec190968): 1
```

**Comment by adamdupuis** [comment]
I'm still new to Node.js... could you explain what express() is now or point me in the right direction? I haven't seen anything like that code anywhere in the guides you have written so far so I'm a little lost.

**Comment by cazala** [comment]
Ah yea, express is just a node server: https://expressjs.com

Nothing different than any server that serves static assets (html, js, css and what not).

You probably have an Nginx, Apache, or something like that, right? If you are serving an html page basically it is the same thing.

I used that because it is the easier way I found to test the scenario of being on an `http://` website and connecting to the proxy via `wss://`

**Comment by cazala** [comment]
ah, you will need certificates for localhost if you want to try that:

```
openssl x509 -req -sha256 -days 365 -in server.csr -signkey server.key -out server.crt
```

And you will need to add them to you trusted certificates..

but basically what I was doing there was connecting to the proxy via `wss://` being on an `http://` page. It should work fine.

**Comment by adamdupuis** [comment]
I generated a LetsEncrypt certificate from some website for the subdomain I'm using the proxy on and then downloaded the certificate and key to the server. Mining works when I access the site from https:// to wss:// but not with http:// to wss:// or http:// to ws://. I am running m.js on a separate server than where I am hosting the proxy.

My proxy.js file looks almost exactly like yours above minus the express portion.

**Comment by adamdupuis** [comment]
I'm not sure what was going on earlier, but I just tried again on http and it worked fine. It's possible my Adblocker was blocking the wasm file (as that is how I block my own miner scripts currently) and I forgot to turn it off for the non-https site. Thanks for your help again, @cazala

**Comment by cazala** [comment]
no problem!
